### ISSUE TITLE
Battery symbol doesn't change, but it does when I create another entity

### ISSUE THREAD

**Issue by bbs2web** [twrecked/hass-aarlo#1018]
Really love the Arlo integration, please keep up the excellent work!

I have a tiny request though, in that the icon for the battery appears to statically be set to use `mdi:battery-50`.

For example:
![image](https://github.com/user-attachments/assets/ce1bb0b6-031e-4ed8-ad50-2bbb8191fb62)

If I however create a template sensor and store the state of the Aarlo integration in it, then it works perfectly:
![image](https://github.com/user-attachments/assets/a789a0a0-d191-4cdf-92a6-b0d1bdfafdc9)

I created this entity using the following entry in the configuration.yaml file:
```
template:
  - sensor:
      - name: 'Arlo - Main gate battery'
        unit_of_measurement: '%'
        device_class: battery
        state: >
          {{ states('sensor.aarlo_battery_level_main_gate') | int(0) }}
```

Result in the Home Assistant dashboard:
![image](https://github.com/user-attachments/assets/8e338bf5-889c-4de6-87df-97e7a122ca77)

Entity card configuration:
```
type: entities
entities:
  - entity: sensor.arlo_main_gate_battery
    name: Main gate
  - entity: sensor.arlo_stables_battery
    name: Stables
  - entity: sensor.arlo_cottage_battery
    name: Cottage
  - entity: sensor.arlo_front_door_battery
    name: Front door
  - entity: sensor.arlo_kitchen_battery
    name: Kitchen
  - entity: sensor.arlo_office_battery
    name: Office
  - entity: sensor.arlo_paddocks_battery
    name: Paddocks
title: Camera battery levels
state_color: true
```
