### ISSUE TITLE
Request snapshot to file snapshotting previous event.

### ISSUE THREAD

**Issue by XmemphistoX** [twrecked/hass-aarlo#103]
Just read one of your automation examples and tested it out.  Is the Arlo Q apable of requesting a snapshot while its recording?  I'm just trying to understand how this works as the snapshots I'm getting seem to be thumbnails from the previous recording.

```
- id: 'automation-0100'
  alias: Camera Snapshot
  trigger:
  - entity_id: camera.aarlo_camera1,camera.aarlo_camera2
    for: 00:00:03
    from: 'idle'
    platform: state
    to: 'recording'
  - entity_id: camera.aarlo_camera1,camera.aarlo_camera2
    for: 00:00:03
    from: 'recently active'
    platform: state
    to: 'recording'
  condition: []
  action:
  - data_template:
      entity_id: "{{ trigger.entity_id }}"
    service: camera.aarlo_request_snapshot
```
