### ISSUE TITLE
Impossible to arm alarm from HA

### ISSUE THREAD

**Issue by antoineguilbert** [twrecked/hass-aarlo#104]
Hey,

I've an issue with this module with alarm control panel. 

When I switch in the Arlo app on my Android from Disarmed to Armed, it's work very well and I can see the state changing in HA. 

But when I try to change from "disarmed" to "armed_away" in HA, nothing happens, it's wait few second and come back to "disarmed". Nothing in the logs.. 

This is my conf : 

```
alarm_control_panel:
  - platform: ifttt
    name: Somfy Home Alarm
    event_arm_away: alarm_arm_away
    event_disarm: alarm_disarm
  - platform: aarlo
    home_mode_name: disarmed
    away_mode_name: armed_away
`````

Do you have any idea ? Do I need a code to arm Arlo ?

Thanks.

**Comment by jxlarrea** [comment]
You have to call the `alarm_control_panel.aarlo_set_mode` service and pass the following:

```json
{
  "entity_id": "alarm_control_panel.aarlo_arlo",
  "mode": "armed"
}
```

**Comment by jxlarrea** [comment]
Try changing `away_mode_name` to `armed `instead of `armed_away`.

**Comment by antoineguilbert** [comment]
I've tried and nothing change. I've restarted HA. 

Now, this : "When I switch in the Arlo app on my Android from Disarmed to Armed, it's work very well and I can see the state changing in HA." doesn't work. 

My setup : I've created a specific account like a friend in Arlo interface to add my HA.

**Comment by jxlarrea** [comment]
Try using the `alarm_control_panel.aarlo_set_mode` service and see if the state changes. You will have to pass the following:

{
  "entity_id": "alarm_control_panel.aarlo_arlo",
  "mode": "armed"
}

Obviously use the correct entity_id if different.

**Comment by twrecked** [comment]
Can you try turning on the pyaalro debug, it should let us know what's happening when you change mode.

```yaml
logger:                                                                                                                              
    default: info                                                                                                                    
    logs:                                                                                                                            
        pyaarlo: debug  
```

**Comment by antoineguilbert** [comment]
Hello,

I've tested some things with week-end. 
Finally, I find a configuration which is working !

```
- platform: aarlo
   home_mode_name: disarmed
   away_mode_name: armed
```

And to arm/disarm the basestation :

```
- service: alarm_control_panel.aarlo_set_mode
   data_template:
      entity_id: alarm_control_panel.aarlo_baie_de_brassage
      mode: "armed"
```

Previously, I used this tab of Home Assistant to try to arm/disarm and this is here that it's not working. 

Image : https://ibb.co/9Tyx13R

Thanks a lot, I think my issue is resolved ! 👍
