### ISSUE TITLE
Charging status gone

### ISSUE THREAD

**Issue by codypet** [twrecked/hass-aarlo#106]
I switched over to HACS and with the move, I lost the ability to see my Arlo Pro camera as charging.  It now just shows a plug instead that doesn't change based on battery level.  Prior to that there was a photo of a battery with a lightning bolt.  That changed when full.

**Comment by twrecked** [comment]
Can you look at camera status and tell me these 4 values:

```yaml
battery_level: 100
battery_tech: Rechargeable
charging: false
charger_type: None
wired: false
wired_only: false
```

The code was modified to make it recognize power supply only but I guess I got it wrong.
