### ISSUE TITLE
camera.record may cause infinite loop

### ISSUE THREAD

**Issue by lisz8** [twrecked/hass-aarlo#1072]
Home Assistant Core: 2024.12.5
OS: 10.5
Arlo: 0.8.1.18
Wired Arlo AVD1001 (A r1.2).

**Description.**

I have this piece of code in an automation:
```
action: camera.record
target:
  entity_id: camera.aarlo_dzwonek
data:
  filename: "{{video_path}}"
  duration: 30
```

It happened that this code failed but the Arlo Integration got into a loop: the state of the entity `"camera.aarlo_dzwonek"` was alternating between `unavailable` and `idle`, the integration kept trying to read the stream from the network, which kept failing again - the loop continued.

The below error repeated every ~2 minutes, and the HA automation got "stuck": it never finished, and I had to restart HA core.
```
homeassistant.components.stream.stream.camera.aarlo_dzwonek
Source: components/stream/__init__.py:448
Integration: Stream
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input, rtsps://18.202.152.47:443/vzmodulelive/[...])
```
---
Edit:
**I can trigger this bug with following setup:**

1) an automation attached to a bell "ding"
2) in this automation, take snapshot to a file, and right away call camera.record
```
action: aarlo.camera_request_snapshot_to_file
target:
  entity_id: camera.aarlo_dzwonek
data:
  filename: "{{ snapshot_path }}"

action: camera.record
target:
  entity_id: camera.aarlo_dzwonek
data:
  filename: "{{video_path}}"
  duration: 30
```

For the recording to succeed, there must be at least 5-6 seconds delay after the bell rang.
_(The bug is not that recording fails but that it causes an infinite loop)_
