### ISSUE TITLE
Please add version tracker for use with Custom Updater

### ISSUE THREAD

**Issue by ronschaeffer** [twrecked/hass-aarlo#12]
Please consider adding a tracker file https://github.com/custom-components/custom_updater/wiki/Notes-for-developers for use with Custom Updater https://github.com/custom-components/custom_updater in order to track availability of new versions. Thanks.

**Comment by arsaboo** [comment]
Hopefully, it will be official soon :)

**Comment by ronschaeffer** [comment]
> Hopefully, it will be official soon :)

Agreed!

**Comment by twrecked** [comment]
I will look into this.

**Comment by arsaboo** [comment]
@twrecked Since this is significantly better than the current HA component, we should move `aarlo` to PyPi and start using that in HA. We can keep adding features over time, but let us not best be the enemy of good :)

**Comment by twrecked** [comment]
I'd love to make it official there are just a couple of things.

- I'm new to python and home assistant and github so I need to work out what's involved in making it official and/or moving things to PyPi.
- The sseclient/requests code bothers me. I've seen it hang up on one person's machine and there isn't an easy way to restart the thing. I want to spend a day or two tidying that up.

And I agree about the "best be the enemy of good", I'm my own worst enemy when it comes to that.

**Comment by Swiftnesses** [comment]
+1 for this, makes life much easier...

**Comment by rccoleman** [comment]
I was about to try to add custom_updater support on a branch and then I saw this.  I can take a stab at building a custom_component.json if you like.

**Comment by rpitera** [comment]
I'm using the paths for the card and component URLs that @rccoleman provided in a recent update (the one's pointing to twrecked's repo) but while I am seeing aarlo-glance, I'm not seeing the components (aarlo or pyaarlo).   This is the config I am using for custom updater:

```
custom_updater:
  track:
    - cards
    - components
  card_urls: 
    - https://raw.githubusercontent.com/ljmerza/calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/maykar/compact-custom-header/master/tracker.json
    - https://raw.githubusercontent.com/twrecked/hass-aarlo/master/custom_cards.json
  component_urls:
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
    - https://raw.githubusercontent.com/twrecked/hass-aarlo/master/custom_components.json
```
It seems correct, but maybe someone can see what I am doing wrong.

**Comment by rccoleman** [comment]
Can you check the log when custom_updater loads, preferably with debug enabled?  It's pretty chatty and helpful.

```
logger:
  default: info
  logs:
     custom_components.custom_updater: debug
     pyupdate: debug
```
In the meantime, I see that I'm still pointing to my repo in my configuration.yaml, so I'll switch it over and see if anything's wrong.
