### ISSUE TITLE
Integration not loading into HassIO

### ISSUE THREAD

**Issue by craigrallen** [twrecked/hass-aarlo#130]
Hi,

The integration was working perfectly and showing the cameras. It has stopped working and will not load into HassIO. No config changes were made to Aarlo, but it now doesn't recognise the entities within HassIO.

![image](https://user-images.githubusercontent.com/56693437/69015900-2db98280-0999-11ea-9996-17ac839dcfb6.png)

The notications shows this

![image](https://user-images.githubusercontent.com/56693437/69015915-4e81d800-0999-11ea-9d4c-22ce197aeb51.png)

I have tried re-installing the integration and also removing the config items from the yaml and adding them back.

The issue started after the recent version update to Home Assistant.

Not sure the best place to look to fix the issue. Please can you advise?

**Comment by twrecked** [comment]
One quick one - do you have `conf_dir` set in your configuration. If you do, can you try removing the line. 

If that doesn't work can you send me your config?

**Comment by craigrallen** [comment]
This is the current active configuration that was working.

```
aarlo:
  username: xxxxxxxxxxxxxxxx - removed 
  password: xxxxxxxxxxxxx - removed
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 2

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed
    trigger_time: 30
    alarm_volume: 8

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength
    
switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    siren_volume: 1
    siren_duration: 10
```
    






This is the log output from the home-assistant.log file (I've pulled out the lines that are related to aarlo and pyaarlo)



2019-11-18 22:44:34 WARNING (SyncWorker_17) [pyaarlo] failed to log in



2019-11-18 22:44:34 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 176, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 131, in setup
    http_connections=http_connections, http_max_size=http_max_size)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 67, in __init__
    self._parse_devices()
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 114, in _parse_devices
    for device in self._devices:
TypeError: 'NoneType' object is not iterable







Let me know if you need anything else
