### ISSUE TITLE
Question: Save recordings to NAS?

### ISSUE THREAD

**Issue by mikesalz** [twrecked/hass-aarlo#136]
Can this component be configured to save clips/streams to a local NAS?  I'm sure the answer will be no, but I figured it is worth asking!

**Comment by twrecked** [comment]
No the component can't be configured to do that. It does support the standard `stream` component and that has (I believe) recording, that might support what you want.

Another way might be to use `appDaemon` or `nodeRed` APIs to get access to the recording library and push images to your NAS device. It might go something like:
1. wait for recording to stop
2. retrieve library recording list
3. download and save any missing recordings
4. repeat

I like `appDaemon` for this stuff but it does require some Python knowledge.

**Comment by mikesalz** [comment]
Thanks for the quick response!  I don't know enough Python to do anything useful.  I think that would be an amazing enhancement to this component.  Maybe something to consider in the future?

**Comment by texiun** [comment]
Giving my appreciation for something like this as well, I’m happy to pipe all streams automatically onto my NAS, I can just organise by date and run a delete command monthly. 

PS - Twrecked, is it possible for me to buy you a coffee?

**Comment by Kras-s-savchiK** [comment]
I have same idea! Can you help me with this?

**Comment by augelr** [comment]
Similar idea for me!
Mine is a bit different. I have an automation now that takes a snapshot from every camera at 9am daily. I'd like to only pull these daily images and put them to a known location.

**Comment by twrecked** [comment]
@augelr Check out `camera_request_snapshot_to_file` - see [here](https://github.com/twrecked/hass-aarlo#services).

**Comment by augelr** [comment]
> @augelr Check out `camera_request_snapshot_to_file` - see [here](https://github.com/twrecked/hass-aarlo#services).

Thanks. I am pretty new to this. I have my Home Assistant sitting on a RPi. I'd like to get the files to my PC (or better yet, Google Drive).  Any advice on how to do this? here is my automation, based on yours. I suppose I change it to camera_request_snapshot_to_file but how to set the proper location? I struggled with this before.

Thanks so much, I really like aarlo, it's great!

alias: Daily Camera Snapshots @9am
description: ''
trigger:
  - entity_id: >-
      camera.aarlo_back,camera.aarlo_front, camera.aarlo_garage,
      camera.aarlo_shed
    for: '00:00:03'
    from: idle
    platform: state
    to: recording
  - entity_id: 'camera.aarlo_camera1,camera.aarlo_camera2'
    for: '00:00:03'
    from: recently active
    platform: state
    to: recording
  - platform: time
    at: '09:00'
condition: []
action:
  - data_template:
      entity_id: >-
        camera.aarlo_back,camera.aarlo_front, camera.aarlo_garage,
        camera.aarlo_shed
    service: camera.aarlo_request_snapshot
mode: single

**Comment by twrecked** [comment]
How to get the files of the raspberry pi is outside the scope of `aarlo`. You could mount a windows share as a way to get the files onto a PC or use `rclone` to sync to Google drive.

This is my automation to save a snapshot to a file:

```yaml
- id: snapshot-to-file
  alias: Camera Snapshot
  trigger:
  - entity_id: camera.aarlo_street_camera
    for: 00:00:05
    from: idle
    platform: state
    to: recording
  - entity_id: camera.aarlo_street_camera
    for: 00:00:05
    from: recently active
    platform: state
    to: recording
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.entity_id }}'
      filename: /tmp/{{ trigger.entity_id }}.jpg
    service: aarlo.camera_request_snapshot_to_file
```
You will need to whitelist the `/tmp` directory.

```yaml
homeassistant:
  ...
  whitelist_external_dirs:
    - /tmp
    - /config
```
