### ISSUE TITLE
aarlo gets stuck every few days

### ISSUE THREAD

**Issue by friendodevil** [twrecked/hass-aarlo#171]
v0.6.8 gets stuck every few (3) days. I've upgraded to 6.9.1.x 6.10 and 6.11 and in some cases the situation was worse: I got consistent performance for ~2 days. 

Resetting home assistant (v105.2) fixes it but I have to cycle resets every ~3 days

**Comment by twrecked** [comment]
Can you paste in your main Aarlo config?

**Comment by friendodevil** [comment]
############################################################
#
# Cameras
#
############################################################
aarlo:
  username: !secret Arlo_USERNAME
  password: !secret Arlo_PASSWORD

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

**Comment by twrecked** [comment]
Can you try with this:

```yaml
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
```

And if you still struggle you can add:

```yaml
  reconnect_every: 90
```

The real issue is the web api we use isn't really designed to hold connection open for a long time.

**Comment by friendodevil** [comment]
tnx. I'll try and circle back in a few days

**Comment by friendodevil** [comment]
added

after 7 days the aarlo does not get stuck anymore

Working code:

```
############################################################
#
# Cameras
#
############################################################
aarlo:
  username: !secret Arlo_USERNAME
  password: !secret Arlo_PASSWORD
  refresh_devices_every: 2
  stream_timeout: 120

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
```
