### ISSUE TITLE
Arlo Baby light and HomeKit integration

### ISSUE THREAD

**Issue by cafedo** [twrecked/hass-aarlo#178]
Hi all,
after the recent updates Arlo Baby light is very nicely integrated in Home Assistant as a light entity. So I share this also as a HomeKit entity: it is recognized in my IOS Home app, I can see the status (switched on/off) but I can't control it and there is the persistent warning "the accessory is not responding".
Are you also suffering this problem?

**Comment by twrecked** [comment]
I don't use Homekit, maybe somebody who does can jump in.

But one thing you can do is turn on debug and see if the request is actually getting through to the Arlo component. Turn on debug with following options and reboot:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo.light: debug
    pyaarlo: debug
```

Look in the log (`/config/homeassistant.log`) for any mention of the light you use it from HomeKit.
