### ISSUE TITLE
Losing connection when router reconnects

### ISSUE THREAD

**Issue by OnkelKeule** [twrecked/hass-aarlo#196]
Hi! 
Firstly I would like to thank you - this is an awesome component! I've been using it for a long time now. For quite a while I have had a problem:
**My router reconnects once every 24h and I'm assigned a new dynamic IP address (this is enforced by my ISP). Whenever this reconnect happens, I lose control over Arlo in this component**: no mode changes, no snapshots, no commands, no updates.

**Only workaround that I found so far: automacially restart HAss whenever a new IP is detected.** While this works fine 99% of the time, it's not a good solution. Now that I found some time during Corona, I wanted to address this issue here.

# configuration.yaml
```sh
aarlo:
  username: !secret arlo_user
  password: !secret arlo_pass
  last_format: '%d.%m. %H:%M'
  mode_api: auto
  refresh_devices_every: 1

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
```

Does anyone have the same problem? What workarounds do you use?
Is there anything I can do? 

Thanks in advance!

**Comment by twrecked** [comment]
Try this config. It should relogin after 120 seconds of inactivity on the event stream.

There should be activity on the stream every 60 seconds because of a keep alive with the Arlo servers so you could lower the value. But putting it too close to 60 could cause disconnects at the wrong time.

```yaml
aarlo:
  username: !secret arlo_user
  password: !secret arlo_pass
  last_format: '%d.%m. %H:%M'
  mode_api: auto
  refresh_devices_every: 1
  stream_timeout: 120
```
