### ISSUE TITLE
State Based Automation Not Triggering On Binary Sensor Event Changes

### ISSUE THREAD

**Issue by MatthewGreen** [twrecked/hass-aarlo#210]
Hello,

Huge Fan of this project, seriously, thank you! I have a question regarding writing some automation based off of the `binary_sensor.<entity_id>`.

I have this automation written below but it never triggers:

```
- id: '1584987065356'
  alias: Patio Light On If Patio Detects Motion
  description: This Automation Should Trigger Only If The Patio Arlo Camera Detects
    Motion During The Night And Before Sunrise
  trigger:
  - entity_id: binary_sensor.aarlo_motion_patio_side
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - data: {}
    entity_id: switch.patio
    service: switch.turn_on
  - data:
      message: The Patio Arlo Camera saw something and turned on the Patio light.
      title: Patio Camera Motion Triggered
    service: notify.notifymobile
```

I did a check on the Developer Tools --> Events --> Listen To Events (state_changed) and I definitely saw that the camera's binary_sensor component moved from "off" to "on" when I walked out there.

Any idea why the automation as written above would not trigger? Thanks!

**Comment by twrecked** [comment]
I'm not that good with actions but I think your indentation might be wrong. See [here](https://community.home-assistant.io/t/solved-automation-editor-simple-turn-on-switch/68654/5). Maybe:

```yaml
 action:
  - data:
      entity_id: switch.patio
    service: switch.turn_on
  - data:
      message: The Patio Arlo Camera saw something and turned on the Patio light.
      title: Patio Camera Motion Triggered
    service: notify.notifymobile
```
