### ISSUE TITLE
Indication that base station is offline

### ISSUE THREAD

**Issue by isoinh** [twrecked/hass-aarlo#231]
Hi,

I'm quite new with Home Assistant but managed to get hass-aarlo working with my setup. The main reason for me to add this was to get notifications if my base station goes offline and currently it seems that I'm not getting any other indication of that except my homeassistant.log file, which states:
`WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}`

Currently my config is:
```
arlo:
  username: !secret arlo_user
  password: !secret arlo_pass
  refresh_devices_every: 1
camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
sensor:
  - platform: aarlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras
      - battery_level
      - signal_strength
```

Am I missing something here?
