### ISSUE TITLE
Detected I/O inside the event loop.

### ISSUE THREAD

**Issue by twrecked** [twrecked/hass-aarlo#243]
This message will appear when you start streaming.

```
2020-05-04 08:06:43 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aarlo doing I/O at custom_components/aarlo/pyaarlo/backend.py, line 79: r = self._session.post(url, json=params, headers=headers, timeout=timeout)
```

It's safe to ignore for now.
* I have a patch to fix the issue but
* I don't believe it's my issue to fix, I think there is an inconsistency/assumption in the base camera code causing the problem. This is from the base camera class.

```python
    async def stream_source(self):
        """Return the source of the stream."""
        return None

    def camera_image(self):
        """Return bytes of camera image."""
        raise NotImplementedError()

    async def async_camera_image(self):
        """Return bytes of camera image."""
        return await self.hass.async_add_job(self.camera_image)
```
I think the assumption was made the stream url is readily available, which isn't the case for Arlo camera. I think we need to add a `def async_stream_source` wrapper that works similarly to the `async_camera_image` function.

**Comment by twrecked** [comment]
Fixed with PR #256 and in release 0.6.19.

Still hoping they tidy the interface...

**Comment by septeven** [comment]
Hi, 
I got this warning today and found this looks-like-closed issue related to the same warning.... 

```
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 16:40:47 (2 occurrences)
Last logged: 17:04:13

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aarlo doing I/O at custom_components/aarlo/pyaarlo/backend.py, line 79: r = self._session.post(url, json=params, headers=headers, timeout=timeout)
```

**Comment by twrecked** [comment]
Are you using any services? What is in the logs on the run up to the error?

**Comment by tyr84** [comment]
Also getting this error, seems to be connected to a bug where hass core freezes

**Comment by twrecked** [comment]
Can  you try using the new Arlo specific services?

https://github.com/twrecked/hass-aarlo#advanced-services

**Comment by tyr84** [comment]
I am only calling services in the aarlo domain. 

I'm unsure of which service is called when i use push category "camera" in a dynamic notification

[https://companion.home-assistant.io/docs/notifications/dynamic-content/](https://companion.home-assistant.io/docs/notifications/dynamic-content/ )

**Comment by tyr84** [comment]
any debuging you would like me to do? I am positive that I'm only using aarlo domain services

**Comment by twrecked** [comment]
We should probably turn on all the [debug](https://github.com/twrecked/hass-aarlo#debugging). This will print out a lot of debug but we are only interested in the lines just before the error message appears. This will tell me what Aarlo was trying to do.

Add this to your configuration and restart:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    custom_components.aarlo.binary_sensor: debug
    custom_components.aarlo.camera: debug
    custom_components.aarlo.light: debug
    custom_components.aarlo.media_player: debug
    custom_components.aarlo.sensor: debug
    custom_components.aarlo.switch: debug
    pyaarlo: debug
```
