### ISSUE TITLE
Camera attributes not updating when new video available

### ISSUE THREAD

**Issue by ajcooper72** [twrecked/hass-aarlo#244]
After a new video is recorded the image_source and video_url attributes are not updating.  I'm trying to build an automation to download new videos so I'm relying on these attributes.

Not seeing any errors in the logs.  If I restart HomeAssistant then the attributes are updated.  Initially thought it might have lost communication to the backend but I can still change the basestation mode.

**Comment by chris-chensy** [comment]
I found a similar issue when I use the image_processing platform for object detection. The image accessed by the platform is mostly out-of-date. They are often from the previous recording. I guess image processing relies on the thumbnail url in the camera property.

**Comment by ajcooper72** [comment]
I'm not doing anything like that, just using the attributes and plugin directly.

**Comment by twrecked** [comment]
What version of Arlo and Home Assistant are you using? And what kind of cameras do you have?

I've seen issue with some cameras just not sending updates to me. 

One thing to try is to add this to your configuration:

```yaml
aarlo:
  no_media_upload: True
```

**Comment by ajcooper72** [comment]
Arlo plugin version:  v0.6.18.15
Home Assistant version:  0.109.6

I have a combination of one Arlo Pro (VMC4030) and 4 original Arlo cameras (VMC3030)

I've added the no_media_upload to my config with no difference.  Here's what my aarlo set up looks like;

```
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 2
  no_media_upload: True
```

**Comment by twrecked** [comment]
Are you ok turning debug on? Add the following to your Home Assistant configuration:

```yaml
logger:
  default: info
  logs:
    pyaarlo: debug
    custom_components.aarlo: debug
    custom_components.aarlo.camera: debug
```

We need to get traces around the time the recording stops. What are looking for is:
* a camera moving to `userStreamActive`
* a `mediaUploadNotification` coming in
* a camera moving to `idle`

This indicates a recording started then stopped. You should then see something setting the last capture and image date fields.

```
2020-05-10 19:01:38 DEBUG (ArloEventStream) [pyaarlo] Front Camera CAMERA got one mediaUploadNotification                           
2020-05-10 19:01:38 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/XXXXXXXXXXXXXX/mediaObjectCount=5713
2020-05-10 19:01:38 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/XXXXXXXXXXX/presignedLastImageUrl=https://arlolastimage-z1.s3.a                                                                                                                                  2020-05-10 19:01:38 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front Camera:presignedLastImageUrl:https://arlolastimage-z1.s3.amazonaws.com/XXXXXXXX
2020-05-10 19:01:38 DEBUG (ArloEventStream) [pyaarlo] Front Camera thumbnail changed        
```
