### ISSUE TITLE
Timestamp Issue

### ISSUE THREAD

**Issue by krelltunez** [twrecked/hass-aarlo#299]
Hi, I've got my Arlo dashboard set up and looking great.  This is a great tool and I'm amazed I didn't find Home Assistant and hass-aarlo a long time ago (I'm a SmartThings convert).

I've worked out almost every issue I've identified, but this one has me stumped.  The timestamps on videos are 7 hours behind my actual time.  I checked both the time zone setting in Home Assistant (it's correct) and in Arlo itself (also correct).  Is there something I need to add the the config file to adjust the reported timestamps?

Thank you, any help you can offer would be MUCH appreciated!

**Comment by twrecked** [comment]
I'll take a look. But I might have to add some debug to the code to help.

And all you should need is the Home Assistant timezone being set. We get the video times from the `Last-Modified` header in the http image response. This is in GMT which we convert to the local timezone. In my case:

```yaml
homeassistant:
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
```
