### ISSUE TITLE
HA crashes with 0.7.0-beta.2

### ISSUE THREAD

**Issue by sebr** [twrecked/hass-aarlo#303]
Hey @twrecked,
Since installing `0.7.0-beta.2`, HA (v 114) crashes consistently. I have identified that it is the `aarlo` camera component, as the crashes only happen when I have the following config:

```
camera:
  - platform: aarlo
    ffmpeg_arguments: "-pred 1 -q:v 2"
```

FWIW, I am not seeing crashes when using the `lights`, `media_platform`, `alarm_control_panel`, `binary_sensor` or `sensor` components – only **`camera`**.

Unfortunately there are no logs which indicate any that has gone wrong - Lovelace just stops responding and my only solution is to restart the docker container.

I am going to try and find a more reliable way to reproduce this, but I'm raising this with you to see if you've experienced anything similar or have any suggestions on how to debug the issue.

**Comment by twrecked** [comment]
What is the last thing that comes out from HA/aarlo?

It could be tied into the duplicate connected ID issue.

**Comment by sebr** [comment]
> What is the last thing that comes out from HA/aarlo?

Nothing of note... only this error from #300 which I think is a red herring as it is peppered all through the logs without any correlation with crashing

```
2020-08-17 15:31:45 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError
Traceback (most recent call last):
  File "/config/custom_components/aarlo/pyaarlo/background.py", line 35, in _run_next
    job['callback'](**job['args'])
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 278, in _refresh_bases
    base.update_modes()
  File "/config/custom_components/aarlo/pyaarlo/base.py", line 253, in update_modes
    props = resp.get('properties', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by twrecked** [comment]
Can you try with the latest updates. I think the issue is ArloBaby I'm just not sure why. Can you try the following config changes to see if they make any difference:

This change will speed up any request timeout. It might help with the lockup.
```yaml
aarlo:
  request_time: 15
```

This change will try to set the alarm mode using v2 of the api, this means the code you saw crashing will never be called.
```yaml
aarlo:
  mode_api: v2
```

One final question, you mentioned not using the alarm because of a naming issue. Can you explain that? I'm thinking of doing per-device configuration and this might be an area I can improve.

**Comment by sebr** [comment]
Still experiencing issues - have seen some of these in the logs just prior to the crashes:

```
2020-08-20 08:39:11 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aarlo doing I/O at custom_components/aarlo/pyaarlo/backend.py, line 79: r = self._session.post(url, json=params, headers=headers, timeout=timeout)
```

**Comment by twrecked** [comment]
I have to look at that. I need to move a bunch of calls behind an async/await pair. 

And you're right, it's probably the service, I'll check it tonight.

**Comment by dfortescue** [comment]
I'm getting the same issue with v0.114.4. Commenting out aarlo from the camera component fixes it for me.

`camera:`
`#  - platform: aarlo`
`#    ffmpeg_arguments: '-pred 1 -q:v 2' `

**Comment by twrecked** [comment]
@dfortescue anything in the logs? It's working for me over here.

Can you try logging in to my.arlo.com with your Home Assistant account and see what is says?

**Comment by staticlama** [comment]
@twrecked Thanks for the reply. I can login to my.arlo.com with the HA account and have no issues. The other part of the integration is working (e.g. I can arm/disarm). For clarity, I have the main "aarlo" component uncommented and that is working as expected:

```yaml
aarlo:
  username: redacted@123.com
  password: redacted
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%d-%m %H:%M'
  refresh_devices_every: 2
  user_agent: linux
```

I'll restart my HA instance this weekend with the camera component enabled and capture the logs to share. I have an automation that triggers a capture on movement, and that crashes HA completely like @sebr .

**Comment by twrecked** [comment]
If you could get logs that would be great. 

One thing, and this is current limitation I'm working on, you can't record for more that 30 seconds with a `user_agent` of `linux`. For recording longer that 30 seconds we attach a hidden stream and Home Assistant can't read MPEG-DASH streams. Can you try without `user_agent` which will break direct play on the Lovelace card.

**Comment by staticlama** [comment]
No worries. This is my config:
```yaml
aarlo:
  username: redacted@123.com
  password: redcacted
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%d-%m %H:%M'
  refresh_devices_every: 2
#  user_agent: linux

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'   
```

When I trigger a recording HA immediately crashes. I have an automation that calls this service:
```yaml
  - data:
      entity_id: camera.aarlo_upstairs_front
      duration: 60
    service: camera.aarlo_start_recording
```

Which immediately crashes HA, and this is the only message in the log:
```
2020-09-19 13:12:50 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aarlo doing I/O at custom_components/aarlo/pyaarlo/backend.py, line 79: r = self._session.post(url, json=params, headers=headers, timeout=timeout)
```
