### ISSUE TITLE
False motion detection related to aarlo_request_snapshot (+ time_zone old settings problem)

### ISSUE THREAD

**Issue by septeven** [twrecked/hass-aarlo#312]
Hello,
I've been encountering false positive for a while now, and I haven't figured out how to stop them to occur. I have Arlo Pro 2 cameras.

First, what I mean by false positive is false motion detection state of my binary_sensor.aarlo_motion_camera where it seems like there's no motion really detected by the camera itself (Arlo app is NOT reporting any motion detection for those false one). 

I recently figured out that the aarlo motion binary_sensor turn on a few seconds only after the aarlo_request_snapshot service has been called - BUT not every time though, which probably makes the troubleshooting more difficult - sure thing is that it seems related as you can see on the screenshot I've attached below.

my aarlo_request_snapshot automation:
```yaml
  - alias: '[SECURITY] Update Arlo Cameras Snapshot'
    initial_state: on
    trigger:
      - platform: time_pattern
        minutes: '/30'
    condition:
    - condition: time
      after: '06:00:00'
      before: '01:00:00'
    action:
      - service: camera.aarlo_request_snapshot
        entity_id: camera.aarlo_cave
```

Look how (false positive) motion is detected a few seconds after the snapshot is taken ..., it is confirmed with the fact that there is no motion detected between 1am and 6am which is because my automation is not running during that specific time window (see automation above). On this screenshot, you can also see that it's not occuring every time the service is called but frequently though (I just circled the 3 one related, but you can easily see on the right that it keeps happening every 30 minutes....)

![Capture d’écran 2020-09-14 à 18 14 53 copie](https://user-images.githubusercontent.com/3216560/93111812-72946f80-f6b7-11ea-997d-557ac57108a4.jpg)

Also, It's not causing me any problem, but I don't understand why only one of my four cameras have the correct timezone setup "time_zone: Europe/Brussels" where the three others have kept my older setting "time_zone: America/New_York" (I was living in Toronto until last year when I moved to France)

**Comment by twrecked** [comment]
I'll take a look at the motion.

As for the timezone, we print the value that Arlo sends us. I have the same issue with one of my cameras, the things shows as "America/Bogota" but the base station is showing as "America/Toronto". All times will be displayed as the timezone set for Home Assistant.

**Comment by twrecked** [comment]
Sorry for the delay, real life got in the way.

You still seeing these phantom events? Can you turn on debugging and look at the logs around when one happened? This should be good:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.camera: debug
    pyaarlo: debug
```
