### ISSUE TITLE
2FA autenticazione SMS

### ISSUE THREAD

**Issue by chavez7** [twrecked/hass-aarlo#316]
I'm Italian and arlo doesn't allow me to post emails for 2-Step Verification. SMS only. I can't figure out what I need to do for this verification method.

**Comment by twrecked** [comment]
Sorry for the delay, I've only just got around to enabling 2FA myself. 

You can't ask for email from the Arlo 2FA set up page but you can when you login. `hass-aarlo` uses this mechanism to ask for an email code. You can only send an email to the address you use for your Arlo login.

In short, enable 2FA and SMS on the Arlo web site, tell `hass-aarlo` to use email and it will ask Arlo to use email regardless.

**Comment by w00master** [comment]
I've gotten this setup to send the code via email.  However, where do I enter the code?  Sorry for missing this, but unfortunately because I've been unable to figure out where to enter the code for 2fa, my Arlo situation on Home Assistant has been disabled.

**Comment by twrecked** [comment]
You configure `hass-aarlo` to go and get the code. Like this, but using your IMAP information.

```yaml
aarlo:
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.host.com
  tfa_username: your-user-name
  tfa_password: your-imap-password
```
