### ISSUE TITLE
Aarlo is not responding

### ISSUE THREAD

**Issue by MechEng70** [twrecked/hass-aarlo#362]
Getting the following error:
`Error: authentication failed
If error persists you might need to change config and restart.`

Have 2FA with the following code:
```
####################################################
#                    AARLO                         #
####################################################
aarlo:
  username: !secret aarlo_username
  password: !secret aarlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  tfa_host: imap.gmail.com
  tfa_username: !secret aarlo_username
  tfa_password: !secret aarlo_email_password
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    trigger_time: 30
    alarm_volume: 8
```

Note: that this was working with 2FA before the 0.118.5 update.  Currently on 2020.12.0 build.

Here is an error in the log:

```
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:562
First occurred: December 13, 2020, 7:44:08 PM (1570 occurrences)
Last logged: 9:30:31 AM

authentication failed
job-error=AttributeError Traceback (most recent call last): File "/config/custom_components/aarlo/pyaarlo/background.py", line 34, in _run_next job["callback"](**job["args"]) File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 302, in _refresh_bases base.update_modes(initial) File "/config/custom_components/aarlo/pyaarlo/base.py", line 338, in update_modes modes = modes.get(self.unique_id, {}) AttributeError: 'NoneType' object has no attribute 'get'
```

Also seeing this error about logging in with the email.  The email used is only for HA to use:
```
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:570
First occurred: December 13, 2020, 8:27:37 PM (1451 occurrences)
Last logged: 8:56:53 AM

logged out? did you log in from elsewhere?
No devices returned from /hmsweb/users/devices?t=1607927252358
No devices returned from /hmsweb/users/devices?t=1607941772449
```

**Comment by MechEng70** [comment]
Also have this in my configuration for logs.  If you know how to get these out of the logs, please let me know..

```
####################################################
#                   LOGGERS                        #
####################################################
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    custom_components.aarlo.camera: debug
    pyaarlo: debug
```
