### ISSUE TITLE
Cannot Specify/Import alarm control panel for mutiple base stations

### ISSUE THREAD

**Issue by sharkpunch5** [twrecked/hass-aarlo#368]
I have both a Arlo Baby and Arlo Base station with cameras, both of these are separately added to Arlo and can be armed/disarmed individually.

When I add the alarm panel to the configuration.yaml using the following default settings it only imports the Arlo Baby but not the other Arlo base station, the ideal behaviour would be that I could import both or specify which to import.

```
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8
```
