### ISSUE TITLE
Arlo without Cloud Subscription

### ISSUE THREAD

**Issue by skilly00** [twrecked/hass-aarlo#376]
Hi sorry if I just missed this in the writeup but I am trying to see if when my Arlo 3 subscription ends if I will still be able to record video with this service or it is only able to do so if I maintain the cloud subscription.  Thanks for all the hard work on this integration!

-Skilly

**Comment by rsunny2012** [comment]
Hello,

can anyone help here. even i dont have cloud subscription but recording all the data in the local sd card ( from base station).  how can i link it up with home assistant

**Comment by twrecked** [comment]
Sorry for the delay getting back. Truthfully, I don't know what will happen. I've always had a cloud subscription.

`aarlo` use the standard web interface so it will get what that gets.

I've got some ideas about saving the streams and so on but it's in very early stages.

**Comment by rsunny2012** [comment]
Hello,

Thanks for the response. All these days i used cloud subscription and use dot get alerts in email and on my app. But paying $10 to this service is not worth. it would be great if you implement the data from sd card ( base station) so that it will be helpful for many people
I have planned to use aarlo with homeassitant in this way. Whenever there is motion detected in the camera, it should alert in email with screenshot or alexa should ring the bell or talk anything.

**Comment by jesserockz** [comment]
I don't have a cloud subscription and i just have my cameras set up to record to the base station USB drive.  I have tried to connect directly to the web server that the base station has to get the local files from like the app does but had no luck so far. Arlo have made it really hard to get in. 

Previously you could get snapshots without a cloud subscription, but at some point Arlo removed that function too so the only option now is the `aarlo` way of streaming and taking a frame, but that is quite slow tbh.

**Comment by rsunny2012** [comment]
lets hope twerecked help us asap

**Comment by twrecked** [comment]
@jesserockz Do you still have the ability to position the camera from the web interface? And does it still work? Because if so, you can try the non-streaming snapshots.

**Comment by rsunny2012** [comment]
without cloud subscription, we can view live feed from the camera and it stores last motion snapshot too. if we want to get the data, we have to click on library, then select Smarthub Base ( if we have cloud subscription, then cloud icon will come and we can instantly view the data if we have connectivity to internet from phone) and then download the video ( at this point, we dont get snapshots of the video) from smarthub base and then we can view

**Comment by jesserockz** [comment]
> @jesserockz Do you still have the ability to position the camera from the web interface? And does it still work? Because if so, you can try the non-streaming snapshots.

Huh, Something must have changed since I last tried this as its working now giving the `fullFrameSnapshot` very quickly. 
Thanks

**Comment by twrecked** [comment]
I tidied up the snapshot code a couple of revisions ago. But keep an eye on it, I've had cameras where the snapshot failed and the cause was Arlo - the website and app positioning failed as well.

**Comment by rsunny2012** [comment]
@twrecked  do you have any update on camera setup without cloud subscription

**Comment by CrouchingWorm** [comment]
Hi folks,
Slightly different question, still related to Aarlo without an Arlo subscription.
I have 9 Arlo's around my place (inside and out). Only one of them have a subscription as it's part of the initial complimentary three month trial.
What I'm seeing is ONLY the Arlo with the active complimentary subscription updates in HA. The other glance cards (and subsequent Deepstack processing) only update when I restart HA.

Is this expected?

It'd be a pity to have to have a subscription on all cameras.
Love this integration and massive thanks for all involved in creating it.

**Comment by jesserockz** [comment]
@CrouchingWorm I don't have a subscription and I get updates from my cameras. Are yours WiFi or base station linked?

**Comment by CrouchingWorm** [comment]
Hi @jesserockz so sorry for the delay in replying.
My camera's are Arlo3 2.5K ones. they're connected via their hub. on their own WiFi channel.
From what I've read on the Arlo forums Arlo won't let you pair their cameras on your own WiFi.
I have two hubs at my place.
I can confirm (at my place) the Arlo app and HA show different images. My car port for example has a different image between the Arlo app compared to HA.
While I've been typing this, I've restarted HA and the images all match now... :(

**Comment by CrouchingWorm** [comment]
Hi again,
I guess this may be a local config issue then? Seems I'm the only one having this issue.
Would it be okay to have someone review my config to see if I've simply made an error?
I'll have a look at the event bus to see if anything fires on movement..
I'll add a subscription to one of my cameras and will make no other changes to my configs to see if they start triggering events..

**Comment by twrecked** [comment]
Post your config, just leave out the sensitive bits!

**Comment by CrouchingWorm** [comment]
Thanks so much!
I let the Arlo app control the motion detection actions, I use the app to store files locally on the attched USB.

Config.yaml
````
  - platform: aarlo
    siren: True
    all_sirens: True
#    snapshot: True
    siren_volume: 9
    siren_duration: 15

  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
 
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    trigger_time: 30
    alarm_volume: 8

light:
  - platform: aarlo
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - connectivity

camera:
  - platform: aarlo
  - platform: local_file
    name: aarlo7snapshot
    file_path: /config/snapshots/arlo7.jpg
##(plus 8 others)##

aarlo:
  username: BLAHBLAH@hotmail.com
  password: !secret hotmail_arlo
  refresh_devices_every: 2
  stream_timeout: 120
  user_agent: Chrome

### I've not been able to use a web browser to see the camera images for some time (this used to be Linux) - Mobile App shows 
camera feeds fine ##
  reconnect_every: 60
  request_timeout: 120
  save_updates_to: /config/snapshots
  media_retry:
  - 5
  - 15
  - 25
  tfa_host: imap-mail.outlook.com
  tfa_username: BLAHBLAH@hotmail.com
  tfa_password: !secret SMTP_notify_password
  stream_snapshot: true
  stream_snapshot_stop: 3
  snapshot_checks: 1
~~~~~~~~~~~~~~~~~~~~~~

automations.yaml
```
- id: 'DetectionID'
  alias: Arlo Detection Stairs
  description: ''
  trigger:
  - event_data:
      entity_id: aarlo.arlo7
    event_type: aarlo_image_updated
    platform: event
  condition:
  - condition: state
    entity_id: alarm_control_panel.aarlo_doukiinternalhub
    state: armed_away
  action:
  - delay: 00:00:20
  - data: {}
    entity_id: image_processing.stairs
    service: image_processing.scan
  mode: single

- id: 'NotificationID'
  alias: Arlo Deepstack Stairs Notification
  description: ''
  trigger:
  - event_data:
      entity_id: image_processing.stairs
      name: person
    event_type: deepstack.object_detected
    platform: event
  condition: []
  action:
  - service: notify.smtp
    data:
      title: Motion Detection
      message: Motion upstairs {{ state_attr('image_processing.stairs','targets_found'),
        state_attr('image_processing.stairs','last_target_detection') }}
      data:
        images:
        - /config/deepstack/arlo7/stairs_latest.jpg
  mode: single
~~~~~~~~~~~~~~~~~~~~~~~~~~
ui-lovelace.yaml
```
    - type: 'custom:aarlo-glance'
      entity: camera.aarlo_arlo7
      name: UStairs
      show:
        - motion
#        - sound
#        - snapshot
        - battery_level
        - signal_strength
        - captured_today
        - image_date
      top_title: false
      top_status: false
      top_date: false
      image_click: play
      light: light.aarlo_arlo7
      play_direct: true
````

If I manually restart HA, manually trigger detection (if there's a snapshot in the arlo app with  person in it), then manually trigger notification it all updates and notifies like I'd hoped it would.
I think the first event on image_updated isn't being detected by my config.. ?

Thanks agin!

**Comment by twrecked** [comment]
You config looks good, it actually looks very similar to mine. The only comment is you might not need to worry about the `user_agent` because the code in the latest betas will pick the best one for the needed action.

In no particular order:

- What version of Home Assistant, `hass-aarlo` and `aarlo-glance` are you using?

- One small thing to try; force a refresh of the lovelace card on your browser - on the page showing the card type `CTRL+SHIFT+I` then `CTRL+SHIFT+R`. That will open the dev tools and make sure the card is up to date.

- Other than that, we need to see some debug logs. Start with these in your `configuration.yaml`, and [here](https://pyaarlo-tfa.appspot.com/) is a (old fashioned looking) webpage you can use to encrypt your logs.

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.camera: debug
    pyaarlo: debug
```
