### ISSUE TITLE
Temperature Parsing/Display Issue

### ISSUE THREAD

**Issue by seanmccabe** [twrecked/hass-aarlo#380]
Getting an issue where the temperature is not displayed correctly, seems the information isn't parsed correctly from the string.

So instead of showing for example 24.1 °C on a card, it is showing:

`{'value': 241, 'alertState': 'high', 'scalingFactor': 10} °C`

Attached a couple of images also.

Do have the alerts on in the Arlo app to alert of high temperate etc. so possibly a result of this?

![InkedInkedScreenshot1_LI](https://user-images.githubusercontent.com/12243212/105782788-fcdfcf00-5fd9-11eb-897b-72f9f224b78a.jpg)
![InkedInkedScreenshot2_LI](https://user-images.githubusercontent.com/12243212/105782804-ff422900-5fd9-11eb-8c77-9f9bd02c972f.jpg)
![Screenshot3](https://user-images.githubusercontent.com/12243212/105782598-b5594300-5fd9-11eb-8f8c-70aa5d896552.png)

**Comment by twrecked** [comment]
I guess Arlo upgraded the BabyCams. I'll take a look at how to deal with this.

**Comment by seanmccabe** [comment]
The issue does diseappear a few minutes later (maybe after the next information update).
So must be a result of the alert set in the app.

**Comment by twrecked** [comment]
I think I have an idea how this is getting through. Can you turn on debug and capture some traces for me?

Add (or modify) this in your config file and restart home assistant. In the logs we are looking for "ambientSensor" or "temperature" or "alertState". I don't need the whole log but if you can get a packet with 'alertState' that would be great.

```yaml

# Add this to your Aarlo config:
aarlo:
  verbose_debug: True

logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.camera: debug
    custom_components.aarlo.sensor: debug
    pyaarlo: debug
```
