### ISSUE TITLE
Arlo Baby cameras - HA stops registering sound and motion

### ISSUE THREAD

**Issue by mikesalz** [twrecked/hass-aarlo#381]
I have two Arlo Baby cameras.  I think this consistently happens to both at the same time... They will periodically completely stop registering motion and sound in HA.  The native Arlo app does register activity, so they do seem to be working correctly.  I noticed that they seem to start working again after a restart, so I configured a nightly restart of the cameras like this:

```
  action:
    - service: aarlo.restart_device
      entity_id: alarm_control_panel.aarlo_kids_room
    - service: aarlo.restart_device
      entity_id: alarm_control_panel.aarlo_that_other_kids_room
```
I am also using `mode_api: v2` in my config.

As of the last couple of days, I just cannot get these things to register sound and motion in HA.  I restarted the cameras in the Arlo app, and even did a hard restart.  This seems similar to [this issue ](https://github.com/twrecked/hass-aarlo/issues/327) but I'm not sure if it is the same.

And by the way, I also have an Arlo Ultra system working through this integration, and it works perfectly.  So it seems to be isolated to the Arlo Baby cameras.  Any thoughts?

**Comment by twrecked** [comment]
Can you paste your `aarlo` config. Minus the personal details obviously!

**Comment by mikesalz** [comment]
Hi @twrecked.  Thanks for the quick response!  This should be all of the relevant pieces from my config:

```
aarlo:
  username: me@email.com
  password: xxxxxxxxx
  mode_api: v2

alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed
    night_mode_name: night

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

binary_sensor:
  - platform: aarlo                                                                                                                   
    monitored_conditions:
      - signal_strength
      - battery_level

light:
  - platform: aarlo
```

**Comment by twrecked** [comment]
Can you try adding this to you `aarlo` config. It could be the back end timing out.

```yaml
aarlo:
  ...
  refresh_devices_every: 2
  stream_timeout: 120
  host: https://myapi.arlo.com
```

**Comment by mikesalz** [comment]
Unfortunately, that did not help.

**Comment by twrecked** [comment]
Can you turn on some debug. With this enabled see we might be able to see what is happening. Looks for errors or disconnects.

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.camera: debug
    custom_components.aarlo.sensor: debug
    pyaarlo: debug
```

**Comment by mikesalz** [comment]
OK... I get a TON of output in the debug.  I'm assuming it's not helpful to paste it all in here.  I don't see anything that looks like errors or disconnects.  Interestingly, I also see mentions of older cameras that I have removed from my Arlo account.  Are those cached in HA somewhere?

I also logged in to my Arlo account through the web and verified that monitoring is turned on and motion alerts are enabled.  Any other ideas or suggestions?  Other than throwing theses Arlo Baby cameras in the trash.

**Comment by twrecked** [comment]
There might be stuff cached. Look for a directory called ".aarlo" where your configuration is, it's safe to delete everything in there.

Do the motion events never work? Or do they stop after a while?

If you want you can share a camera with me and I'll take a look. Just point it at a wall or the street or something you don't care about.

**Comment by mikesalz** [comment]
Typically they work for some number of days and then stop.  Adding the nightly camera restart seemed to help that.  But as of this week, they don't seem to be working at all.

I don't mind temporarily sharing a camera with you.  I think I'll just need your email address, right?

**Comment by mikesalz** [comment]
So this is weird... I deleted the aarlo.pickle file from the cache directory and restarted HA.  My son was in his room when HA came back up.  It picked up motion for the first time in days.  But then it stopped working again.  Not sure if the motion was related to the cache file removal or not, but it did work for a moment!

**Comment by mikesalz** [comment]
Hey @twrecked, just wondering if you had any more thoughts on this?  Maybe it is just something weird with my setup?

**Comment by twrecked** [comment]
Sorry, I was meant to ask you to share a camera with me - steve.herrell@gmail.com - and I'll take a look.

**Comment by mikesalz** [comment]
I appreciate it @twrecked !  I shared one camera with you.  For privacy, I deleted all recordings and pointed it toward some legos.  Obviously, it won't pick up any motion this way.  So please let me know if/when you'd like me to create some motion for the sensor to pick up.  Thanks again for all of your help!

**Comment by twrecked** [comment]
I've added them and I'm going to leave my Home Assistant running. If you just want to make some random motion every we can see when they stop.

I have jobs to do around the house so I'm going to keep it running and check the logs once in a while.

I did notice one thing, I added a fix to stop the Essential cameras from draining and it probably broke the Baby Cam connectivity. Basically, you have to ping the device every minutes and I stopped it for battery powered wifi devices but I should have made an exception for the Baby Cam.

**Comment by mikesalz** [comment]
I have added some random motion a few times over the past 10 minutes.  Let me know what you see on your end.

Interesting point about the Essential cameras.  I wonder if that caused the issue!

**Comment by twrecked** [comment]
Did the cameras work until about 6 days ago?

**Comment by mikesalz** [comment]
Yeah! It stopped last week sometime.

**Comment by mikesalz** [comment]
Oh, so you ARE seeing the motion events? Strange because I am not.

**Comment by twrecked** [comment]
I haven't see once since about 11.12.

I'll push the baby cam fix.

**Comment by PysX** [comment]
I could say i have the same issue. I can have the video stream but no more other sensors temperature, humidity, ...
Can't set alarm or light.  I think it started on recent security update of HA (not sure)

Thanks for working on it !

**Comment by mikesalz** [comment]
As a test, I reverted back to version 0.7.0.5.  Everything started working again.  So it does seem to be isolated to version 0.7.0.6.  At least for my instance.

**Comment by twrecked** [comment]
I just pushed 0.7.0.7; can you try it?

Also, the temperature sensors seems broken. Do you use those?

**Comment by PysX** [comment]
Seems have fixed the issue!

**Comment by mikesalz** [comment]
Looks like it is working! Thank you so much!!

**Comment by twrecked** [comment]
Excellent.

**Comment by twrecked** [comment]
If it's working feel free to unshare the camera! I have to run some errands so won't be around for an hour or two.

**Comment by mikesalz** [comment]
@twrecked My two Arlo Baby motion sensors stopped working again this week.  The motion sensors are still working, though.  Could it have something to do with the recent changes you made for doorbell sound?

**Comment by twrecked** [comment]
It shouldn't have - it's in a different area of the code - but anything is possible.

Which user agent do you use? I did make some changes in that area as well.

And which piece has stopped working? You say motion is still working, is it just the video?

**Comment by mikesalz** [comment]
Sorry, I probably wasn't specific enough.  I am not referring to video.  I'm referring to the motion sensor and sound sensor.  And as far as user agent, I have not explicitly configured that.  Here is my config:  

```
aarlo:
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  mode_api: v2
  refresh_devices_every: 2
  stream_timeout: 120
  host: https://myapi.arlo.com
```
