### ISSUE TITLE
Could not find base stations for device...

### ISSUE THREAD

**Issue by Luticus** [twrecked/hass-aarlo#392]
I keep getting an error in the logs that says: "Could not find base stations for device [device name]" in my home assistant logs. 

1:30:36 PMmessage first occurred at 1:10:36 PM and shows up 20 times

I see messages like this in the 'full log':  
2021-02-16 12:55:38 ERROR (MainThread) [pyaarlo] Could not find any base stations for device
2021-02-16 12:55:39 ERROR (ArloBackgroundWorker) [pyaarlo] Could not find any base stations for device

I'm not sure if I'm doing anything wrong.

I'm using a vm install of Home Assistant and I use this config:

```
aarlo:
  username: <user>
  password: <pass>
  hide_deprecated_services: true
#  refresh_devices_every: 2
#  stream_timeout:120
#  reconnect_every: 90
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
#  conf_dir: /config/.aarlo
  no_media_upload: True
  mode_api: auto
  refresh_devices_every: 10
  http_connections: 5
  http_max_size: 10

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 1

binary_sensor:
  - platform: aarlo
 ```
  
  I've tested a few different variations of this with no luck. I do see cameras in my interface but they are not live feeds. It will playback the last clip from the cams. The connected sensors for the cams all say disconnected though and on the camera outputs it always seems to say "unavailable". Is this correct or am I missing something?
