### ISSUE TITLE
Unable to view Aarlo_Glance cards via any Web Client

### ISSUE THREAD

**Issue by CrouchingWorm** [twrecked/hass-aarlo#413]
Hi there,
I'm unable to view Aarlo Glance camera images on any of my web browsers, or machines.
The cards work a treat on iOS devices.
The images simply don't display. Other 'camera' images do display on the same page, just not aarlo_glance ones.
I've attached an encrypted log output from Chrome (via Control+Shift+I) here:
[console logs aarlo glance.txt](https://github.com/twrecked/hass-aarlo/files/6113259/console.logs.aarlo.glance.txt)
Also caught this in the web console:
:8123/images/arlo-glance-01.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
![image](https://user-images.githubusercontent.com/35030235/110579436-8c1ffb00-81b2-11eb-8420-429097ed1ae8.png)
![image](https://user-images.githubusercontent.com/35030235/110579454-95a96300-81b2-11eb-9f0b-58f5d553b058.png)
[HA-1615353077428.txt](https://github.com/twrecked/hass-aarlo/files/6113370/HA-1615353077428.txt)

I'm running version  v0.2-alpha.22 of the Front End integration.
And v0.7.1.beta.6 for the Arlo Camera Support Integration.
A sample config snippet for the glance card is below:
````
    - type: 'custom:aarlo-glance'
      entity: camera.aarlo_arlo1
      name: Front Door
      image_view: direct
      image_top: 'name,status'
      image_bottom: 'motion,library,stream,snapshot,battery'
      image_click: 'stream'
      library_sizes: '3,4,2'
````
I used to run (same issue):
````
    - type: 'custom:aarlo-glance'
      entity: camera.aarlo_arlo1
      name: Front
      show:
        - motion
        - snapshot
        - battery_level
        - signal_strength
        - captured_today
        - image_date
      top_title: false
      top_status: false
      top_date: false
      image_click: play
      light: light.aarlo_arlo1
      play_direct: true
````
This has worked in the past..

My web sessions look like this:
![image](https://user-images.githubusercontent.com/35030235/110578564-da33ff00-81b0-11eb-8fb6-c3487a6bde5a.png)
I'm able to streem when I trigger a request (including going to full screen). When I tell it to stop streaming it goes back to the image above, with "Recently Active" displayed in the top right corner of the camera feed I selected.
@twrecked confirmed I'm running the latest version of the glance card (thanks so much).

I've tried turning off ad blockers, no luck.
**Full disclosure:**
I've also noticed my web browser seems to time out after 'a period of time', that is elements in the page fail to refresh. This is across all of my lovelace pages. However the Arlo_glance cards never load via any browser or computer in my instance. Mobile (iOS) is fine.

It'd be fab to get this working.

Thanks!

**Comment by CrouchingWorm** [comment]
Sorry, potentially dumb question..
By browser logs you mean the console output?

**Comment by twrecked** [comment]
Yes. Sorry.

**Comment by twrecked** [comment]
One more thing to try might be setting your user agent in `configuration.yaml`. I wonder if it's sending the wrong format image back.

```yaml
aarlo:
 ...
  user_agent: linux
```
