### ISSUE TITLE
2FA not working anymore?

### ISSUE THREAD

**Issue by zygote279** [twrecked/hass-aarlo#419]
I'm not sure if there's been a breaking change or if there's something I've done that I've just spotted, but aarlo is failing authentication now so nothing's working...!

I've got the below as my config:
```
aarlo:
  tfa_host: imap.gmail.com
  tfa_username: !secret arlo_2fa_username  
  tfa_password: !secret arlo_2fa_password
  refresh_devices_every: 2
  stream_timeout: 120
```

And have it set up as sensors and cameras.

All was working fine, but just failing to authenticate.

Anything look odd about above config?

Only other thought might be I'm using the multiple email ability of gmail - ie using myemail+arlo@gmail.com rather than setting up a completely separate email address - just wondering if this might cause any validation/login issues?

**Comment by twrecked** [comment]
The + shouldn't be a problem.

You do have a username and password set?

```yaml
aarlo:
  username:
  password:
```
