### ISSUE TITLE
Aarlo not picking up changes in Arlo Portal 

### ISSUE THREAD

**Issue by nickolas1969** [twrecked/hass-aarlo#421]
Having just moved houses and re-installed all my 7 cameras, I had to change the names to match the new locations. The account I use for HA sees these updates, and all 7 cameras. But the Integration does not. How do I get it to refresh that information so that I have all 7 camera's reading the correct names and entities (like battery left)?

**Comment by twrecked** [comment]
I honestly thought they would just appear. Can you double check the HA account on the Arlo web site? Make sure the names on the main screen match the ones in the config.

If that looks good we need to turn on some debug. In `configuration.yaml` add the following:

```yaml
aarlo:
  verbose_debug: True

logger:
  default: info
  logs:
    custom_components.aarlo.camera: debug
    pyaarlo: debug
```
