### ISSUE TITLE
Extreme drain overnight

### ISSUE THREAD

**Issue by DerHerzog7** [twrecked/hass-aarlo#433]
I've been having issues with extreme battery drain on my doorbell overnight. I had to replace my doorbell for another reason, so it was freshly charged and put in yesterday.

I contacted Arlo and they reviewed the logs - "Before the video doorbell drain its battery last April 12. It recorded a total of 596 minutes of camera usage. With 444 minutes of it is from livestreaming and 152 minutes of motion detection from 12 am to 7pm of April 12, 2021. The recommended usage of the camera battery is only 5 minutes recordings/livestreaming per day."

It looks like the integration kept the doorbell camera alive for a significant amount of time overnight?

It's possible my motion detection is just too high - something that I'll adjust. However, is there an issue in the current release regarding continuous streaming?

**Comment by twrecked** [comment]
What kind of doorbell is it? And how it connected? We used to have an issue with draining certain types of doorbells by pinging them too often. You can turn on logs and see what is happening, add this to `configuration.yaml` and reboot:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    pyaarlo: debug
```

If you want me to take a look you can paste the logs into [here](https://pyaarlo-tfa.appspot.com/) and then paste that output to here.
