### ISSUE TITLE
ID already exists - ignoring binary sensor. 

### ISSUE THREAD

**Issue by DerHerzog7** [twrecked/hass-aarlo#436]
Any idea why I am getting this error on restart?

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:497
Integration: Binary sensor (documentation, issues)
First occurred: April 21, 2021, 10:04:22 AM (2 occurrences)
Last logged: April 21, 2021, 10:04:22 AM

Platform aarlo does not generate unique IDs. ID motion_doorbell already exists - ignoring binary_sensor.aarlo_motion_doorbell
Platform aarlo does not generate unique IDs. ID connected_doorbell already exists - ignoring binary_sensor.aarlo_connected_doorbell

**Comment by bslefevre** [comment]
Getting the same error overhere!

**Comment by twrecked** [comment]
I'm going to need some more logs, see [here](https://github.com/twrecked/hass-aarlo#debugging) for instructions. And you can encrypt it [here](https://pyaarlo-tfa.appspot.com/) but remember you still need to attach that output to this bug report.

This should be enough debug to help:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.binary_sensor: debug
    pyaarlo: debug
```
