### ISSUE TITLE
Authentication failing with no config or account changes - running 2021.6.0b5

### ISSUE THREAD

**Issue by townsmcp** [twrecked/hass-aarlo#448]
I have updated HA to latest beta version (core-2021.6.0b5) (aarlo was working fine on 2021.5.5) and on reboot im getting the following error message in the logs:

```
2021-06-02 12:53:51 ERROR (SyncWorker_0) [pyaarlo] authentication failed
2021-06-02 12:53:51 ERROR (SyncWorker_0) [custom_components.aarlo] unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
```
Im running aarlo 0.7.1.beta.15. Tried doing a reinstall and reboot of HA but still getting the above issue.

To confirm:

- The seperate Arlo account that I setup for HA access to the cameras has access enabled.
- I can log in to the account using the HA username and password, at which point a 2fa message is sent to my gmail account.
- I can access the gmail account without issues.
- I can see the authentication code and recieve new codes in the email account just after a reboot of HA.

My config is:

```
aarlo:
  username: !secret aarlo_usr
  password: !secret aarlo_pwd
  user_agent: linux
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  stream_snapshot: False
  last_format: "%m-%d %H:%M"
  refresh_devices_every: 6 # was set to '2'
  stream_timeout: 120
  reconnect_every: 240 # was set to '90'
  tfa_host: imap.gmail.com
  tfa_username: !secret aarlo_tfa_usr
  tfa_password: !secret aarlo_tfa_pwd

media_player:
  - platform: aarlo

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

binary_sensor:
- platform: aarlo
  monitored_conditions:
    - motion
    - sound
    - ding

sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality
```

Any thoughts?

**Comment by twrecked** [comment]
I just upgraded to `2021.7.0.dev20210602` and it's working for me. Can you turn on extra logging and capture the output before the  `authentication failed`, it might give us a hint. Something like this should work:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    pyaarlo: debug
```
