### ISSUE TITLE
Arlo 2FA

### ISSUE THREAD

**Issue by stevepridemore** [twrecked/hass-aarlo#450]
I have found that you can now disable Arlo 2FA after it has been enabled.

**Comment by twrecked** [comment]
Funnily enough I noticed I managed to turn it off on one of my test accounts and it kept working. I'll add a note to the docs.

**Comment by AlanStout** [comment]
How do you disable it then please

**Comment by twrecked** [comment]
You used to be able to do it from the website but it looks like it's gone. I'll poke around and see if I can find it.

**Comment by webbpage** [comment]
It is not possible to disable 2FA as of July 2021. I just got off the phone with Arlo support to confirm. I tried to create a new account but that also forces 2FA before even accessing the my.Arlo dashboard.

**Comment by wierts** [comment]
Hi, 
I have the same issue that i cannot get my Arlo to work. The message i get is 2fa failed. I have a seprate gmail account just for the homeassistant integration. i added all the additional info in my configuration.yaml file

any suggestion are welcome

Below my yaml file

 ```
 tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: HomeassistantArloDnM@gmail.com
  tfa_password: Password
```

**Comment by twrecked** [comment]
You might need another option:

```yaml
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret imap_username
  tfa_password: !secret imap_password
```

**Comment by mikesalz** [comment]
Maybe this is a dumb question... Is the tfa_ username and password the same as the existing username and password attributes?  Or would it be your email credentials?

**Comment by mikesalz** [comment]
I am having a lot of trouble with this as well.  Below is my config and the error message I am receiving.  Please tell me what dumb thing I am doing!

```
aarlo:
  username: [my email]@gmail.com
  password: [my Arlo password]
  mode_api: v2
  refresh_devices_every: 2
  stream_timeout: 120
  host: https://myapi.arlo.com
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.host.com
  tfa_username: [my email]@gmail.com
  tfa_password: [My gmail password]
```

```

unable to connect to Arlo: attempt=4,sleep=120,error=authentication failed
unable to connect to Arlo: attempt=5,sleep=240,error=authentication failed
unable to connect to Arlo: attempt=6,sleep=300,error=authentication failed
unable to connect to Arlo: attempt=7,sleep=300,error=2fa no suitable secondary choice available
unable to connect to Arlo: attempt=8,sleep=300,error=2fa no suitable secondary choice available
```
