### ISSUE TITLE
Entities are updated without change triggering automations

### ISSUE THREAD

**Issue by kyletpugh** [twrecked/hass-aarlo#456]
Entities appear to be updated whenever the connection is re-established. For instance, creating an automation with a trigger on Last Camera's Thumbnail url attribute will get triggered when HA is restarted or for me every day at midnight. The automation is triggered for every camera at once. The entity should only update when it has a different value.

**Comment by twrecked** [comment]
I think this should be quite easy, I know the old state, I know the new, so only fire if really changed. I'll take a look.

**Comment by kyletpugh** [comment]
Cool. Thanks!

**Comment by twrecked** [comment]
As I mentioned in the other bug this one is more complicated than I first thought. 

When you say "ha is restarted" do you mean a reboot every night at midnight? And is it every attribute or just the `thumbnail_url`? I suspect it's just that one because I don't keep its value across reboots.

**Comment by kyletpugh** [comment]
Yeah it gets triggered after a reboot because it does not have a value. I'm unsure why it doesn't store the value though. I can deal with the reboot it's not a big deal since I'm most likely going to cause that. The random update for the same value is causing it to trigger the automation. Basically I just have an automation with a trigger on the state of thumbnail_url of every last camera. I bet if you make an automation like that then you will start getting it triggered at random times. I thought it was the authentication so I checked the email, it's only used for this with a device password. The authentication it's requested almost every for hours. The problem happens when the authentication expires or fails. So last night I got it twice, 8pm and 12am, there's no authentication after 4pm. Yet I got notifications this morning and the integration is still working. The HA core log is filled with errors about authentication failing after the last success. It's still working but it's lagging my entire house now.... I'm thinking that there may be no good solution for Arlo cameras and I might just change since I'm getting sick of the multiple daily emails trying to sell me stuff as well.

**Comment by twrecked** [comment]
Try 0.7.2, it should help with the authentication emails. But I hear you about the promo emails, I'm grandfathered into an old plan so there is no way I'd move to the new plans, I have no idea why they keep trying.

The value doesn't get saved because it's the only piece of information I never thought to save. So, as you've found out, it gets blanked on a reboot.

Can you paste in your automation, I'll give it a try here and make sure it fixes your issue. Can you also paste in an example of your authentication issue logs and your main config (minus the sensitive bits obviously).

**Comment by kyletpugh** [comment]
It looks like 0.7.1.2 is the latest? I think that's what you meant but it appears to have significantly improved performance since I was sitting at 25+% memory usage and now I am back down to the around 9% it usually is. 

I have the plan that came with my system, I think that's what you mean. Or do you have the old plan and they still let you keep it? I just downgraded back to the accompanying plan that came with my system. The new paid plan takes hours to analyze a video routinely, it's not worth any amount of money and they refuse to devote any resources to improving anything instead just throwing out "new" camera systems and blasting promo emails. Anyway... lol

I wasn't thinking and did not grab the logs before I upgraded all the integration, HA, debian, and restarted... They were just like a pretty generic one or two lines that said authentication failed for 2fa or something like that but it was hundreds of times in only hours.

Here is a simple version of the automation. I want to add the wait for trigger for the events for the response of the notification so I can directly launch an intent for the video but this works for now as there are usually multiple by the time I can even respond. I renamed some personal stuff to generic names but you have to change that anyway...

```
alias: Motion Detected by Camera
description: 'Notify of motion detection by camera'
trigger:
  - platform: state
    entity_id: sensor.aarlo_last_camera_1
    attribute: video_url
  - platform: state
    entity_id: sensor.aarlo_last_camera_2
    attribute: video_url
  - platform: state
    entity_id: sensor.aarlo_last_camera_3
    attribute: video_url
  - platform: state
    entity_id: sensor.aarlo_last_camera_4
    attribute: video_url
condition: []
action:
  - service: notify.mobile_app
    data_template:
      title: '{{ trigger.to_state.name.replace(''Last '', '''') }}'
      message: Motion detected at {{ as_timestamp(now()) | timestamp_custom('%I:%M %p') }}
      data:
        image: '{{ trigger.to_state.attributes.thumbnail_url }}'
        ttl: 0
        group: motion
        priority: high
        importance: high
        clickAction: {{ trigger.entity_id.replace('sensor.aarlo_last_','') }}
        actions:
          - action: URI
            title: Watch Live
            uri: /{{ trigger.entity_id.replace('sensor.aarlo_last_', '') }}
          - action: URI
            title: Watch Recording
            uri: '{{ trigger.to_state.attributes.video_url }}'
mode: parallel
max: 10
```
