### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by pinkfloydFR** [twrecked/hass-aarlo#471]
Seen in my log :

2021-07-26 22:00:00 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aarlo doing I/O at custom_components/aarlo/pyaarlo/backend.py, line 137: r = self._session.get(

2021-07-26 22:00:00 WARNING (MainThread) [pyaarlo] request-error=RuntimeError

Rasberry 4 / HA OS / All updated

**Comment by twrecked** [comment]
Thanks. I'll take a look.

What version of Home Assistant are you on?

**Comment by pinkfloydFR** [comment]
Core Version : core-2021.7.4 on Home Assistant OS 6.1.

Thk !

**Comment by twrecked** [comment]
(Of course) I'm not seeing it here.

Had the system been up for a while or are there any other logs near that might help identify the issue.

If it's reproducible can you turn on debug for `pyaarlo` and we can see what is happening just before.

**Comment by pinkfloydFR** [comment]
no more warning for now, i will check it and inform you if it appear again.

**Comment by pinkfloydFR** [comment]
One again !
2021-07-27 16:32:16 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aarlo doing I/O at custom_components/aarlo/pyaarlo/backend.py, line 137: r = self._session.get(
2021-07-27 16:32:16 WARNING (MainThread) [pyaarlo] request-error=RuntimeError

and i remember ! yesterday i change my config from  : 

```
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
```

to 

```
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  user_agent: apple
  recent_time: 10
  stream_snapshot: True
  refresh_devices_every: 1
  stream_timeout: 120
  reconnect_every: 90
  stream_snapshot_stop: 3
```

( to try correct the snapshot problem )

**Comment by twrecked** [comment]
Can you turn on debugging, I need to know what happened just before the warning log. Something like this should do it:

```yaml
logger:
    default: info
    logs:
        pyaarlo: debug
        custom_components.aarlo: debug
```
