### ISSUE TITLE
Battery drain within a few hours

### ISSUE THREAD

**Issue by marcuswhit** [twrecked/hass-aarlo#475]
I've just setup the Aarlo plugin in the past day for my 4 cameras, and all seemed like it was working great. But then they all went from near full charge to flat overnight. 

Today I had to reinstall my Home Assistant OS anew (for unrelated reasons), and hence also did for Aarlo too, with all the default suggested settings - but I only added one of the cameras back in for now. So today I had two cameras going, with only one integrated with the fresh install of Aarlo. 

The result is the same for both cameras with a heavy battery drop over several hours. Attached image shows the battery drain from the one integrated. There is limited movement during this time, so typically the cameras would be asleep - this issue has only surfaced since integrating with Aarlo the first time yesterday. I'm assuming at this stage that even though I didn't integrate my second camera with the new Aarlo install today, it must have had something changed the first time around which is keeping it awake?

Any suggestions? I'm using it with two Pro 4's and two Essentials, and the issue seems the same. 

Thanks. 

![Screenshot_2021-08-05-19-07-37-03_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/2963426/128335889-8deb948b-18f6-40de-a77e-ff12e77deefc.jpg)

**Comment by twrecked** [comment]
Can you send the model numbers of the cameras and can you paste your config - the non sensitive bits obviously.

Also, is there anything in the logs?

**Comment by marcuswhit** [comment]
Sure - the models are two of the Arlo Pro 4, and Arlo Essential Spotlight Camera - both current models bought 2 months ago.

Config for the dashboard widget is:

```
type: custom:aarlo-glance
entity: camera.aarlo_driveway
name: Driveway
show:
  - motion
  - sound
  - snapshot
  - battery_level
  - signal_strength
  - captured_today
  - image_date
top_title: true
top_status: true
top_date: true
image_click: play
```

The HA config is as follows - I've done almost nothing with the fresh install other than setup Aarlo and enable remote access.

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

aarlo:
  username: !secret arlo_user
  password: !secret arlo_pwd
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret gmail_user
  tfa_password: !secret gmail_pwd

camera:
  - platform: aarlo

sensor:
  - platform: aarlo
    monitored_conditions:
      - total_cameras
      - last_capture
      - recent_activity
      - captured_today
      - battery_level
      - signal_strength
      - temperature
      - humidity
      - air_quality
```

It's worth noting that the first time I installed it I did include the optional args for the Aarlo config as follows, which I didn't include this time in case that was causing the battery drain:
```
  refresh_devices_every: 2
  stream_timeout: 120
```

**Comment by simdevmat** [comment]
Also experiencing the same issue. After setting this up last night, battery on my Pro 3 Floodlight is near flat. Using default aarlo config with aarlo-glance-card

**Comment by twrecked** [comment]
Can you both send me the model numbers. And can I ask, does the device appear as its own base station?

I ask because some battery based base stations shouldn't be polled. I have a check to determine this but I may need to update it.

**Comment by simdevmat** [comment]
> Can you both send me the model numbers. And can I ask, does the device appear as its own base station?
> 
> I ask because some battery based base stations shouldn't be polled. I have a check to determine this but I may need to update it.

https://www.arlo.com/nz/products/arlo-pro-3-floodlight.aspx
Hardware number: FB1001AerH4

It's a standalone camera with no base station.

**Comment by twrecked** [comment]
I don't have one of these cameras, can I bother you for some more information? If you look at the `Developer Tools > States` for one of the floodlights, can you send me the following values (obviously, your values will be different):

```yaml
battery_level: 45
battery_tech: Rechargeable
brightness: 0
charging: false
charger_type: None
wired: false
wired_only: false
```

You don't need to paste these, but are the parent ID and device ID the same?

Thanks.

**Comment by simdevmat** [comment]
Yea they are the same

device_id: A3X1057XA079A
model_id: FB1001A
parent_id: A3X1057XA079A

**Comment by twrecked** [comment]
I think I have an idea how to fix the floodlight. I'll try some code out.

**Comment by marcuswhit** [comment]
Hi - the camera models I have are:
- VMC2030AerH8 - https://www.arlo.com/au/products/arlo-essential/default.aspx
- VMC4041PAerH3 - https://www.arlo.com/au/products/arlo-pro-4/default.aspx

All are standalone cameras without a base station.  Re your question above, the parent ID and device ID are the same for each.

Since my last post I've reset the cameras, added them again into Arlo and Aarlo/HA, with just the default config, and the result is the same - the battery drains to empty over half a day or so.  Interestingly though, for at least one of them the drain didn't really start straight away after recharging - it was ok for several hours, then around 10pm last night it went to empty pretty quickly.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/2963426/128584849-bc47c281-bc6f-4eac-8461-9fa3b3482db2.png">

**Comment by twrecked** [comment]
I just created 0.7.1.4 with a possible fix. If it still doesn't work can you paste this information from the camera states:

```yaml
battery_level:
battery_tech:
charging:
charger_type:
wired:
wired_only:
wifi:
corded:
```

**Comment by NickM-27** [comment]
Wanted to add to this, I am also experiencing the same issue. Just updated to 0.7.1.4 and will report in a few hours how much they drained.

I have 3 of these: VMC2030AerH8 - https://www.arlo.com/au/products/arlo-essential/default.aspx

Here is that information you asked for just in case:

`battery_level: 37
battery_tech: Rechargeable
charging: false
charger_type: None
wired: false
wired_only: false
wifi: true
corded: false`

**Comment by twrecked** [comment]
That's great info. I think the wifi being `false` was causing the issue. I ignore it for the essential cameras now.

If anybody has `pyaarlo` logging and verbose debug turned on can you look for the phrase `NO ping to`. It should be skipped for the Essential cameras. Config is something like this:

```yaml
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  verbose_debug: True

logger:
  default: info
  logs:
    pyaarlo: debug
```

**Comment by NickM-27** [comment]
I don't have the debugging on, but wanted to say when I initially enabled aarlo two hours ago the cameras dropped in battery but they have been steady now for 2 hours after that so seams like at least an improvement.

**Comment by NickM-27** [comment]
Another update, looks good: 
![Screen Shot 2021-08-07 at 8 46 07 PM](https://user-images.githubusercontent.com/14866235/128618134-5320f073-ac04-42eb-85df-7ab5c39c7fe8.png)

**Comment by simdevmat** [comment]
Im still seeing reasonable battery use. Been running the update for 24hs.

![image](https://user-images.githubusercontent.com/4081224/128651507-a702eae8-e07f-49af-b085-bfb2d2c42c99.png)

```yaml
model_name: FB1001A
brand: Netgear Arlo
battery_level: 22
battery_tech: Rechargeable
brightness: 2
flipped: true
mirrored: true
motion_detection_sensitivity: 80
power_save_mode: best_video
signal_strength: 3
unseen_videos: 0
recent_activity: false
image_source: snapshot/08-09 13:00
charging: false
charger_type: None
wired: false
wired_only: false
wifi: false
corded: false
attribution: Data provided by my.arlo.com
model_id: FB1001A
siren: true
supported_features: 0
```
