### ISSUE TITLE
Alarm control panel can't change modes for wired doorbell

### ISSUE THREAD

**Issue by dejan2101** [twrecked/hass-aarlo#480]
Hi,

i have a wired doorbell and in an alarm control panel (in HA) it changes modes when i change it in app but i can't change modes from HA. Is this not supported or am i doing something wrong?

**Comment by twrecked** [comment]
If you can do it from the web interface you can do it from this integration. Can you turn on debugging and see what happens:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    custom_components.aarlo.camera: debug
    pyaarlo: debug
```

**Comment by dejan2101** [comment]
I removed HA user and re-added - it was working right from the start but stops after a minute or so.

Logs:
2021-08-11 17:42:17 DEBUG (SyncWorker_4) [custom_components.aarlo.alarm_control_panel] Front door set mode to disarmed
2021-08-11 17:42:17 DEBUG (SyncWorker_4) [pyaarlo] set:ArloBase/A2G305K5A1CFF/activeSchedule=None
2021-08-11 17:42:17 DEBUG (SyncWorker_4) [pyaarlo] Front door:new-mode=disarmed,id=mode0
2021-08-11 17:42:17 DEBUG (SyncWorker_4) [pyaarlo] v2 arming
2021-08-11 17:43:03 DEBUG (ArloEventStream) [pyaarlo] sseclient-error=ChunkedEncodingError
2021-08-11 17:43:06 DEBUG (ArloEventStream) [pyaarlo] Fetching device list after ev-reconnect

**Comment by twrecked** [comment]
This might be related to another issue I'm seeing where I send the wrong packet in. In the meantime can you turn on verbose debug.

```yaml
aarlo:
  ...
  verbose_debug: True
```
