### ISSUE TITLE
2FA Using imap with a custom port

### ISSUE THREAD

**Issue by BuggaHouse** [twrecked/hass-aarlo#481]
Hi, I'm not using Gmail for my Arlo account and my provider is using another port. 

Is it possible to expose a config for a custom port to match my email provider?

thanks

**Comment by twrecked** [comment]
I'll push a fix later this week. You'll be able to specify the port by putting it at the end of the host, something like this:

```yaml
aarlo:
  ..
  tfa_host: yourimaphost.com:4444
```
