### ISSUE TITLE
New HA infrastructure requires services.yaml?

### ISSUE THREAD

**Issue by Swiftnesses** [twrecked/hass-aarlo#50]
Hi Steve,

It seems plugins now require a simple services.yaml, example (taken from another plugin!):

```
# Example services.yaml entry

#  SPDX-License-Identifier: Apache-2.0
update_last_called:
  # Description of the service
  description: Forces update of last_called echo device for each Alexa account.
  # Different fields that your service accepts
  fields:
    # Key of the field
    email:
      # Description of the field
      description: List of Alexa accounts to update. If empty, will update all known accounts
      # Example value that can be passed for this field
      example: 'my_email@alexa.com'
```

Do we need this for the Aarlo services?

**Comment by Swiftnesses** [comment]
Here's another:

```
# Example services.yaml entry

set_variable:
  # Description of the service
  description: Update a variables value and/or its attributes.
  # Different fields that your service accepts
  fields:
    # Key of the field
    variable:
      description: string (required) The name of the variable to update
    value:
      description: any (optional) New value to set
    value_template:
      description: template (optional) New value to set from a template
    attributes:
      description: dictionary (optional) Attributes to set or update
    attributes_template:
      description: template (optional) Attributes to set or update from a template ( should return a json object )
    replace_attributes:
      description: boolean ( optional ) Replace or merge current attributes (default false = merge)
```
