### ISSUE TITLE
Library Delay of 30 minutes

### ISSUE THREAD

**Issue by georgejung** [twrecked/hass-aarlo#502]
I have noticed that there is a delay of approximately 30 minutes before a new clip is sent to the library and subsequently downloaded. It's been like this for a long time, i've been using it since February or so and i'm not sure if the library has ever updated on its own.

The 'status' on my lovelace card is updated rightaway and shows recording, and then it goes to recently active and the snapshot is updated right away but my library never has the latest clip...
My streaming works fine.

If I restart HA it updates the library right away. I feel like i'm missing something incredibly obvious but i did spend some time looking through the issues and again at the docs before posting :) Thanks for your great work

Here is my config for the relevant sections. I am using alarm though I didn't put it below, and light.
```
aarlo:
    username: !secret arlo_email
    password: !secret aarlo_pw
    refresh_devices_every: 2
    stream_timeout: 120
    tfa_host: imap.gmail.com
    tfa_username: !secret email
    tfa_password: !secret pw
    save_media_to: "/config/media/${SN}/${Y}/${m}/${d}/${T}"
    save_updates_to: "/config/media_still/${SN}/${Y}/${m}/${d}/${T}"

camera:
  - platform: aarlo

sensor:
   - platform: aarlo
     monitored_conditions:
     - total_cameras
     - last_capture
     - recent_activity
     - captured_today
     - battery_level
     - signal_strength
     - temperature
     - humidity
     - air_quality
    
switch:
   - platform: aarlo
     siren: True
     all_sirens: True
     snapshot: True
     doorbell_silence: True
     siren_volume: 1
     siren_duration: 10

```
