### ISSUE TITLE
Arlo (wired) doorbell no motion and ding events

### ISSUE THREAD

**Issue by Frankniesten** [twrecked/hass-aarlo#517]
Hello,

Thanks for your work to make an nice HA component!

I configured my Arlo wired doorbell and everything is working fine (Authentication, MFA etc.) 
Except the sensors in particulary the motion sensor en the Ding.

Some more info:
- I use an seperate Arlo account for Aaarlo with admin privileges.
- When I start HA the last doorbell snapshot is loaded and visible.
- I can use the switches in HA to update for example doorbell_silence. The status get updated in the Arlo app.
- In the logs file I see activity (authentication and basic info form my doorbell) with no errors.
- I can't find motion or ding objects in the log file.

My configuration:

Version:  0.7.1.7

Configuration:

aarlo:
  username: ***
  password: ***
  user_agent: linux
  verbose_debug: True
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_source: imap
  tfa_type: email
  tfa_host: ***
  tfa_username: ***
  tfa_password: ***

camera:
  - platform: aarlo
  
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    - connectivity

switch:
  - platform: aarlo
    doorbell_silence: True

sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength

logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    custom_components.aarlo.binary_sensor: debug
    custom_components.aarlo.camera: debug
    custom_components.aarlo.light: debug
    custom_components.aarlo.media_player: debug
    custom_components.aarlo.sensor: debug
    custom_components.aarlo.switch: debug
    pyaarlo: debug

Any suggestions?

**Comment by Frankniesten** [comment]
When i restart the HASS. The event stream is sometimes working for a couple of minutes and are working in HASS. After a couple of minutes de event stream stops working.

**Comment by twrecked** [comment]
Sorry for the delay getting back. So, that `recoveredDocument` piece is new, I'm not getting anything like that on my system which means I maybe missing a piece. It also means means we might need to use Chrome to work out what has changed.

For starters, can you get some debug. Turn on these settings and run until the problem happens:

```yaml
aarlo:
  ... your existing config
  verbose_debug: True

logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    custom_components.aarlo.binary_sensor: debug
    custom_components.aarlo.camera: debug
    custom_components.aarlo.light: debug
    custom_components.aarlo.media_player: debug
    custom_components.aarlo.sensor: debug
    custom_components.aarlo.switch: debug
    pyaarlo: debug
```   

If you want to strip out the non Aarlo stuff you can run the following
command on the Home Assistant logs.

```sh
egrep '(aarlo|^  |^\{)' home-assistant.log > aarlo.log
```

[This Section](https://github.com/twrecked/hass-aarlo#hiding-sensitive-data) of the docs explains how to hide the data so only I can see it. You'll need to copy and paste the output to a file and attach that to these comments.
