### ISSUE TITLE
Nothing getting logged on new install

### ISSUE THREAD

**Issue by snowboardjoe** [twrecked/hass-aarlo#523]
Been running HA (2021.11.3) for about a month now and slowly adding more integrations. Got this installed today (v0.7.1.8), but nothing is getting logged at all from this module. I expected to at least see an email from Arlo to verify the 2FA, but nothing has showed up indicating it's not even able to login. Not seeing any devices yet. Here's my current configuration:

```
aarlo:
  host: https://my.arlo.com/
  username: '[redacted]@pobox.com'
  password: '[redacted]'
  tfa_host: 'mail.pobox.com'
  tfa_username: '[redacted]@pobox.com'
  tfa_password: '[redacted]'
  refresh_devices_every: 2
  stream_timeout: 120
  verbose_debug: true
  user_agent: linux
```

Any other suggestions on how to debug this issue?

**Comment by oskarax** [comment]
i have exactly the same issue and i find this in the log

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:591
Integration: Arlo Camera Support (documentation, issues)
First occurred: 11:29:52 (1 occurrences)
Last logged: 11:29:52

No devices returned from /hmsweb/users/devices?t=1637317792030

**Comment by psu1989** [comment]
Mine was working for weeks and then stopped yesterday

Logger: homeassistant.setup
Source: /usr/local/lib/python3.9/asyncio/events.py:80
First occurred: 8:45:11 AM (1 occurrences)
Last logged: 8:45:11 AM

Setup of aarlo is taking over 10 seconds.

**Comment by NickM-27** [comment]
Have you added this to the base `configuration.yaml` ?

```
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    custom_components.aarlo.camera: debug
    pyaarlo: debug
```
