### ISSUE TITLE
Not Na issue, more around use of this integration

### ISSUE THREAD

**Issue by cloudbr34k84** [twrecked/hass-aarlo#562]
im trying to understand how this integration will work or i can make it work better than just viewing the cameras

I have smart subscriptions enabled as well for now, not sure if its needed now i have HA integrated

In the Arlo App, i mainly use the schedule mode. I have a custom mode activated between 9pm and 5am then from 5am to 9pm is another customer mode.

1. Because im using schedule mode, does it matter about the below too much
```
# Alarm Control Panal
alarm_control_panel:
  - platform: aarlo
    away_mode_name: Armed
    home_mode_name: schedule
    disarmed_mode_name: Disarmed
    trigger_time: 30
    alarm_volume: 8
```
2. should i turn off notifications in the arlo app and automations in HA for the cameras..

Any guidance or suggestions would be greatly appreciated asd i just cant wrap my head around how to use this integration
