### ISSUE TITLE
Should I be able to download a Snapshot on Motion to my media folder?

### ISSUE THREAD

**Issue by TheStigh** [twrecked/hass-aarlo#568]
Hi @twrecked 

Have I misunderstood, or should I be able to have a snapshot (image) taken upon motion - then a video stream - and save both to the defined folder? I can see video files in the folder but no images.

I have an **Arlo Essentials** without hub.

My `configuration.yaml`:
```
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_user
  password: !secret arlo_pass
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 2
  verbose_debug: True
  tfa_source: imap
  tfa_type: email
  tfa_host: 'imap.gmail.com'
  tfa_username: !secret GV_USER
  tfa_password: !secret GV_PASS 
  save_media_to: "/media/Arlo/${N}/${Y}/${m}/${d}"
  stream_snapshot: true
  snapshot_checks: 3
  snapshot_timeout: 60
```

Just to make sure I haven't done anything wrong, I include my `aarlo-glance` card config:
```
          - type: 'custom:aarlo-glance'
            entity: camera.aarlo_inngang
            name: Inngang
            image_view: 'direct,modal'
            #image_click: stream
            image_top: 'name,status'
            image_bottom: 'library,signal,sound,stream|snapshot,battery'
            image_click: stream
            library_size: '3,4,2'
            snapshot_retry: 5
            library_view: modal
```
