### ISSUE TITLE
Arlo Baybycam will not live stream

### ISSUE THREAD

**Issue by ddromnes** [twrecked/hass-aarlo#574]
I hav configured the aarlo to my Arlo Babycam. Every sensor works perfectly, but the live stream just woun't work. I'm using the lovelace-hass-arlo card but when i click the image it just loads. Im able to see captured videos and last captured, but no live stream. Whan can be the issue?

**Comment by twrecked** [comment]
What are you trying to stream on? It's probably a user agent issue.

**Comment by ghostsam45** [comment]
same issue as ddromnes at Chrome Version 100.0.4896.60 (Build officiel) (64 bits)

**Comment by ejkreboot** [comment]
I am having the same behavior on my Arlo Essentials indoor camera. I get a still image when the card opens, and click replays a saved video (despite having it set to "stream"). I am running aarlo version 0.7.2b8.3 on HassOS 8.0 on raspberry pi 3 version B. (I have no Hub, just the camera). I have tested on both Chrome and Firefox running on MacOS 12.3.1.

Here is my config:
```
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: push
  tfa_type: PUSH
  stream_snapshot: True
  stream_snapshot_stop: 5
  snapshot_checks: [1,5]
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
```

And the card's yaml:
```
type: custom:aarlo-glance
entities:
  - entity: camera.aarlo_room_4
image-click: stream
image-view: direct
```
I set the log level to debug, but I did not see anything informative in the logs.

Anything else I can do to debug or investigate?
