### ISSUE TITLE
Motion detection Stopped or frozen

### ISSUE THREAD

**Issue by sambeetm** [twrecked/hass-aarlo#590]
All my five Pro2 cameras' motion detection is frozen for last 20 Hours. They are either stuck at Clear or Detected status. Restarting Arlo or HA multiple times did not help.

**Comment by twrecked** [comment]
Can you try changing the backend? Use `sse`, see [here](https://github.com/twrecked/hass-aarlo#missing-events).

I think Arlo is playing around with something.

**Comment by sambeetm** [comment]
Yes, adding 'backend: sse' resolved the issue. Thanks.

**Comment by mikesalz** [comment]
I have the same issue.  I added `backend: sse` but it still doesn't seem to work.  Sound is detected; Just not motion.  This is for both an Arlo Ultra system and Arlo Baby cameras.

```
aarlo:
  username: XXXXXX@XXXXXXX.com
  password: XXXXXXX
  mode_api: v2
  backend: sse
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: XXXXXX@XXXXXXX.com
  tfa_password: XXXXXXXXX
```
