### ISSUE TITLE
How to arm/disarm cameras only?

### ISSUE THREAD

**Issue by garyo** [twrecked/hass-aarlo#621]
I have aarlo set up on my HA. I have only cameras, no Arlo alarm or control panel or basestation or anything. Just some cameras.
I can see the cameras in HA (and their connectivity, battery status etc.) so it's all working OK.
I set `backend: sse` as suggested here.

My question is how to arm/disarm the cameras? I don't see a service or switch for that.
(If there is a forum where I should ask questions rather than creating an issue, please let me know.)

**Comment by garyo** [comment]
I figured it out. I have to set up an `alarm_control_panel` even though I have no hardware for that. It essentially becomes a virtual alarm control panel in HA.
```
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
```
Then this action in an automation works:
```
  - service: aarlo.alarm_set_mode
    data:
      entity_id: alarm_control_panel.aarlo_front_door
      mode: Armed
```

(I note that the away mode is still called "Armed Away" in the UI; would love to have that just say "Armed" but that's a tiny thing.)
