### ISSUE TITLE
Temperature reading "stuck" in Celsius

### ISSUE THREAD

**Issue by pdfowler** [twrecked/hass-aarlo#623]
There are several issues related to temperature sensors switching from F -> C (see below) around the 2022.5.5 release. I've tried nearly every workaround, but my arlo baby was still outputting its value as Celsius. 

I finally found a workaround involving a template. Hopefully this helps someone

```
sensor:
  - platform: template
    sensors:
      arlo_temperature_alt:
        value_template: "{{ states('sensor.aarlo_temperature_main') }}"
        unit_of_measurement: "°C"
        device_class: "temperature"
        friendly_name: "Main Temperature (Alt)"
        availability_template: >-
          {%- if not is_state("sensor.aarlo_temperature_main", "unavailable") %}
            true
          {%- endif %}
```

### Related Issues:
* https://github.com/home-assistant/core/issues/72625
* https://github.com/home-assistant/core/issues/73459
* https://github.com/home-assistant/core/issues/71770
