### ISSUE TITLE
New cameras don't update

### ISSUE THREAD

**Issue by codypet** [twrecked/hass-aarlo#63]
I've used this for about a month now and its worked great.   Recently I changed one of the cameras to an Arlo Pro, and now I cannot get the HA interface to recognize the new camera much less get it so show up.   Is there something I need to do to get the new camera to show?  It shows up on the Arlo website fine and its viewable like the other cameras are.  I should note that the other Arlo Pro cameras on the same account are working just fine.

**Comment by twrecked** [comment]
Can you update and try again? I noticed an issue with the Arlo not sending me packets I need to determine devices. (Not sure the issue was mine or Arlo changing the back end.)

**Comment by codypet** [comment]
Should I be updating the whole HA instance or just replace the files from your repository?  I did restart HA and its still having the same problem.

**Comment by twrecked** [comment]
Just replace my files. It will go something like:
* `git pull` on the `aarlo` repository
* re-install the files (`./install go <where-you-put-stuff-your-config>`)
* stop home assistant
* start home assistant

And hopefully you'll see the new cameras.

**Comment by codypet** [comment]
Unfortunately, I'm still seeing just the old cameras.

**Comment by twrecked** [comment]
Crap. Are you ok to turn on some debug. I'll be able to see exactly what it thinks is happening. Add this to your configuration file:

```yaml
logger:
    default: info
    logs:
      custom_components.aarlo.alarm_control_panel: debug
      custom_components.aarlo.binary_sensor: debug
      custom_components.aarlo.camera: debug
      custom_components.aarlo.sensor: debug
      pyaarlo: debug
```

It will put some extra info into `config/home-assistant.log`.
