### ISSUE TITLE
At night still have the images of this afternoon

### ISSUE THREAD

**Issue by reefnl80** [twrecked/hass-aarlo#647]
Hi all,

hoe can help me, I have the aarlo intergration running, but the screenshots are not refreshing. 

At the moment it is 21:56 pm but still have the images of dat time. Please see picture below 
![image](https://user-images.githubusercontent.com/82978117/197869591-c63ae526-3e92-4d4f-b4df-143fb6e68a2e.jpg)

hope anybody can help me

**Comment by twrecked** [comment]
I have to ask, but has anything happened to cause them to refresh? Arlo won't refresh the image unless it has "seen" something.

If so and they are not updating can you post in your `aarlo:` config.

**Comment by twrecked** [comment]
Also, add this to you config:

```yaml
refresh_devices_every: 2
stream_timeout: 120
reconnect_every: 90
backend: sse
```
