### ISSUE TITLE
Sorry I am really stupid... after receive code from arlo... where I have to put it?

### ISSUE THREAD

**Issue by platini76** [twrecked/hass-aarlo#661]
please help I did not find right place.

**Comment by twrecked** [comment]
Do you mean the code in the email? You have to [set up 2fa to get it working](https://github.com/twrecked/hass-aarlo#2fa)

**Comment by platini76** [comment]
I have intalles extension from Hassio and then insert in configuration.yaml  this:


aarlo:
  username: ________
  password: _________
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_host: imap._____.it
  tfa_username: _______t
  tfa_password: ________


now I receive tons of emails and I don't know where I have to pot this code....

**Comment by twrecked** [comment]
You can ignore them, the code will read them automatically for you.

Can you see your cameras?

**Comment by platini76** [comment]
Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:462
Integration: aarlo ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 04:00:15 (92 occurrences)
Last logged: 12:52:53

unable to connect to Arlo: attempt=88,sleep=300,error=2fa core retrieval failed
unable to connect to Arlo: attempt=89,sleep=300,error=2fa core retrieval failed
unable to connect to Arlo: attempt=90,sleep=300,error=2fa core retrieval failed
unable to connect to Arlo: attempt=91,sleep=300,error=2fa core retrieval failed
unable to connect to Arlo: attempt=92,sleep=300,error=2fa core retrieval failed

**Comment by twrecked** [comment]
You 2FA authentication is failing. Make sure you have all the pieces in your config:

```yaml
aarlo:
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.host.com
  tfa_username: your-user-name
  tfa_password: your-imap-password
```

And double check the `tfa_username` and `tfa_password`, they probably aren't the same as your _Arlo_ login.

If that all looks correct then turn on debug:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    pyaarlo: debug
```

And add this to your current `aarlo` config:

```yaml
aarlo:
  # old config
  verbose_debug: True
```

And then restart, you will get more information on why it's failing.
