### ISSUE TITLE
Snapshots not updating after internet loss, requires HASS restart.

### ISSUE THREAD

**Issue by devitus** [twrecked/hass-aarlo#683]
Hi everyone,

I've been having the following issue with the hass-aarlo integration as of late. My internet provider is highly unreliable with a few daily outages (no alternatives available locally unfortunately). Following such outages, the integration continues working in general, but thumbnails stop updating on the aarlo-glance card on my wall panel dashboard.

This is the aarlo integration from my config file (sensitive elements redacted):

```
aarlo:
  username: xxxx
  password: xxxx
  backend: sse
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: xxxx
  tfa_password: xxxx
  reconnect_every: 90
  user_agent: linux
  no_media_upload: True
```

This is the automation I use to request new snapshots from all three cameras every 5 minutes:

```
alias: Aarlo Snapshots (5 min)
description: ""
trigger:
  - platform: time_pattern
    minutes: /5
condition: []
action:
  - service: aarlo.camera_request_snapshot
    data:
      entity_id: camera.aarlo_front_gate_camera
  - service: aarlo.camera_request_snapshot
    data:
      entity_id: camera.aarlo_front_door_camera
  - service: aarlo.camera_request_snapshot
    data:
      entity_id: camera.aarlo_back_camera
mode: restart
```

Currently the only working method of getting the thumbnails to refresh again on the aarlo-glance card is a full HASS restart. All aarlo-related entities - cameras, base stations, etc. - continue reporting their states, there are no "unknowns". 

The only difference I've noticed after such outage is that after running the snapshot automation the "image_source:" and the "AWSAccessKeyID" parameters of the cameras remain unchanged. E.g. "image_source" would get stuck on "image_source: snapshot/01-09 23:40" and "AWSAccessKeyID" would display the same value, even though normally the "Signature=" element would normally change when things work normally. All the while my automations that change the state of base stations to "armed_away", "disarmed", etc. would continue to work. So it would appear that the integration still remains authenticated with Arlo API.

I've enabled the logs ("debug") for the cameras, but have not noticed any differences between the logs during normal working state and the cases when thumbnails get "stuck".

Is there anything in the logs I should pay attention to to provide better evidence, or would anyone happen to have a suggestion on a fix?

Thanks in advance!
