### ISSUE TITLE
ERROR (ArloEventStream) [pyaarlo] SSE RESPONSE?{"status":"connected"}

### ISSUE THREAD

**Issue by jurgenweber** [twrecked/hass-aarlo#696]
Hi, I restarted today and this integration has stopped working, sorry. Lots of errors like the topic.. Seemingly normal things are failing.

```
2023-01-30 20:41:23.543 ERROR (ArloBackgroundWorker) [pyaarlo] unable to read mode, try forcing v2
2023-01-30 20:41:24.385 ERROR (ArloEventStream) [pyaarlo] SSE RESPONSE?{"resource":"cameras","properties":[{"interfaceVersion":5,"serialNumber":"serialnumber","batteryLevel":100,"signalStrength":4,"brightness":0,"mirror":false,"flip":false,"zoom":{"topleftx":0,"toplefty":0,"bottomrightx":1280,"bottomrighty":720},"mic":{"mute":false,"volume":100},"speaker":{"mute":false,"volume":58},"talk":{"mute":false,"volume":100},"streamingMode":"eventBased","continuousStreamState":"inactive","motion":{"sensitivity":5,"zones":[]},"resolution":{"width":848,"height":480},"idleLedEnable":false,"lowBatteryLedEnable":false,"privacyActive":false,"standbyActive":false,"setupActive":false,"connectionState":"available","activityState":"idle","swVersion":"1.13.2.1_91_8c8c8ff_44ab9bd","hwVersion":"6","modelId":"ABC1000","motionSetupModeEnabled":false,"motionSetupModeSensitivity":80,"motionDetected":false,"audioDetected":false,"hasStreamed":true,"nightLight":{"enabled":true,"brightness":128,"mode":"rgb","rgb":{"red":32,"green":64,"blue":128},"sleepTime":0,"sleepTimeRel":0},"fov":110,"audioAnalytics":{"babyCryDetection":{"enabled":true,"triggered":false}},"olsonTimeZone":"Australia/Sydney","name":"","nightVisionMode":1,"videoMode":"superWide","hdr":"auto","blockNotifications":{"block":false,"duration":0,"endTime":0},"bestLocalLiveStreaming":"off"}],"action":"is","transId":"web!40e975f1-f106-4ca3-a8a7-4b38448acdc7","to":"69CSR7J-114-32406860_web","from":"50C176SP443A1"}
```

yaml config

```
aarlo:
  backend: sse # https://github.com/twrecked/hass-aarlo#missing-events
  # https://github.com/twrecked/hass-aarlo#best-practises-and-known-limitations
  username: my username
  password: !secret arlo_pass # verbose_debug: True
  reconnect_every: 45 # minutes, detault 90
  request_timeout: 30 # seconds, default 120
  refresh_devices_every: 1 # hours, default 3
  stream_timeout: 110 # default 180s
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com:993
  tfa_username: email address
  tfa_password: !secret email_password
  ```
