### ISSUE TITLE
"No scheme supplied" when TFA using API

### ISSUE THREAD

**Issue by robbanl** [twrecked/hass-aarlo#786]
Having an issue with the python error message "No scheme supplied". Tried to specify the domain with http/https, but that just broke everything, even when I escaped the slashes "http:\/\/domain". I don't have good enough Python skills to fix this, but my solution was a temporary hack, adding "https://" infront of {} on these lines:

https://github.com/twrecked/hass-aarlo/blob/version-0.7.x/custom_components/aarlo/pyaarlo/tfa.py#L179

https://github.com/twrecked/hass-aarlo/blob/version-0.7.x/custom_components/aarlo/pyaarlo/tfa.py#L206

Guessing this might have something todo with Python version? Or have I configured it incorrect?

```
  tfa_host: "my-domain-has-a-dash.maindomain.tld"
```

**Comment by twrecked** [comment]
Can you paste in your full config - with the sensitive bits obscured -  you shouldn't be going through that piece of code if you're trying for IMAP.

**Comment by robbanl** [comment]
Hello. It isn't SMTP but API/SMS for Arlo TFA. Arlo will send an SMS, my server "my.host.name" will capture it, parse the code and return it when the API is called. The real domain name i'm using is a subdomain, like the dummy host (my.host.name). This domain is a real FQDN and it's accessible from the internet.

```
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_source: rest-api
  tfa_type: SMS
  **tfa_host: "my.host.name"**
  tfa_username: dummy-user
  tfa_password: dummy-pass
  backend: sse
  verbose_debug: True
  packet_dump: True
```
