### ISSUE TITLE
Cloudflare blocking access, changed user agent didn't work

### ISSUE THREAD

**Issue by squirtbrnr** [twrecked/hass-aarlo#787]
Starting sometime on 8/6 the integration went unavailable for me.  When I rebooted HA I get an authentication error in my logs and the aarlo integration fails to setup.  I regenerated my app password for my gmail account for 2fa.  I confirmed I could log into my Arlo account with the same credentials this integration is using.  I changed my aarlo config to a very bare bones config and it could not authenticate.  I'm enabling debug and rebooting and should have logs later.  What logs are needed?

```
This error originated from a custom integration.

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:165
Integration: aarlo (documentation, issues)
First occurred: 10:23:48 PM (4 occurrences)
Last logged: 10:25:44 PM

authentication failed
```

My config:
```
aarlo:
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret arlo_tfa_username
  tfa_password: !secret arlo_tfa_password
  username: !secret arlo_username
  password: !secret arlo_password
  reconnect_every: 90
```
