### ISSUE TITLE
TFA - imap connection failed[Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by KalleHoppe** [twrecked/hass-aarlo#796]
Hi, i want to start by thanking @twrecked for all the great work and effort into this project. 
I was one of the many that had issues with the 2fa changes solved in issue #778, and I got it working... for some time, until sometime this week when i started to get this error in the logs during 2fa authentication process:

```code
imap connection failed[Errno -2] Name does not resolve
2fa startup failed
```
I suppose it can't resolve the imap url for the API, but I don't know for sure that is the url that is failing.
How can I find the has-aarlo logs so I can verify? I can only manage to see the HA logs, not the detailed ones. 
Is there any one else getting this issue?

My configuration looks like this:
```yaml
aarlo:
  username: !secret arlo_gmail_username
  password: !secret arlo_password
  mode_api: auto
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_username: !secret arlo_gmail_username
  tfa_password: !secret arlo_gmail_app_password
  verbose_debug: True

  tfa_source: imap
  tfa_type: email
  host: https://my.arlo.com
```

**Comment by twrecked** [comment]
It looks like a resolver issue. What is your `tfa_host` set to?

**Comment by KalleHoppe** [comment]
Yeah, exactly.
I was told in the other 2-fa thread to remove the tfa_host property from the config, so I only have the host property set as in my comment.
Should I have both host and tfa_host configured?

**Comment by twrecked** [comment]
Yes. One configures authentication with Arlo and the second one tells us
how to collect the 2FA code that authentication generates.

You don't usually need to change the non tfa one.

**Comment by KalleHoppe** [comment]
ok, thanks for the explanation. 
I added the tfa_host: imap.gmail.com. So the config looks like this now
````yaml
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  mode_api: auto
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_username: !secret arlo_gmail_username
  tfa_password: !secret arlo_gmail_app_password
  verbose_debug: True

  tfa_source: imap
  tfa_type: email
  host: https://my.arlo.com
  tfa_host: imap.gmail.com
````
to the config, but now I'm getting this error, below. So I guess I'm back to the same issue as in #778. Sorry I can't find a more detailed error message in the logs :/
```code
body-error=JSONDecodeError
authentication failed
```

**Comment by KalleHoppe** [comment]
Ok, this is wierd. Even though I got that json error, it now seems that the authentication was successful and it's working again! I haven't done anything since my previous message.

**Comment by ramdisk00** [comment]
I also have issues with aarlo / arlo, it stopped working a month or so with the tfa thing. I followed the recommendations modifying background file in both spots and setup the google email tfa, no luck here. Not sure where to start to look to see if tfa is working.

this is one of my errors:

```
body-error=JSONDecodeError
No locations returned from /hmsdevicemanagement/users/5HS5-336-66351581/locations
```


this is my alro config

```
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_ha_user
  password: !secret arlo_ha_password
  mode_api: auto
  verbose_debug: True
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret arlo_tfa_user
  tfa_password: !secret arlo_tfa_password
```

I also get "unavailable" on all of my arlo entities, which in the past I did not get.
