### ISSUE TITLE
2FA 

### ISSUE THREAD

**Issue by brianveno827** [twrecked/hass-aarlo#798]
I have had good luck with this integration but I had to restart my HACS.  The 2FA failed on the beta version so I deleted the pickle.  Now my aarlo isn't even generating a new pickle.  what could be the problem?

**Comment by twrecked** [comment]
Can you post your config? Or can you check if `save_session` is disabled?

**Comment by ramdisk00** [comment]
I can't seam to get 2fa to work either, been trying for weeks now no luck

```
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_ha_user
  password: !secret arlo_ha_password
  backend: sse
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret arlo_tfa_user
  tfa_password: !secret arlo_tfa_password
```
I also setup gmail 2fa and got the password and still nothing
