### ISSUE TITLE
Automation to record multiple cameras

### ISSUE THREAD

**Issue by evilalmus** [twrecked/hass-aarlo#799]
I'm fairly new to HA so this may be an easy/.obvious question.
I'm trying to setup an automation to record multiple aarlo cameras when a motion sensor moved from "clear" to "on"
The built-in "camera.record" service takes "duration" and "filename" in the "data" block and supports multiple entity_id's (and the action would look something like this):
```
service: camera.record
data:
  duration: 120
  lookback: 30
  filename: /media/filename.mp4
target:
  entity_id:
    - camera.aarlo_g33kbar_driveway
    - camera.aarlo_g33kbar_doorbell

```
is there any way to do this with the `aarlo.camera_start_recording` service?
