### ISSUE TITLE
problem with aarlo

### ISSUE THREAD

**Issue by unecc** [twrecked/hass-aarlo#809]
Hi to all, still works?
I've this error

![image](https://github.com/twrecked/hass-aarlo/assets/134554559/88631e6a-bc0a-4b7b-ab96-fb1284a09a1c)

**Comment by twrecked** [comment]
Arlo is playing around. Try adding this to your config:

```yaml
aarlo:
 .. your original config
 mqtt_host: mqtt-cluster-z1.arloxcld.com
```

**Comment by unecc** [comment]
Thanks for your fast replay. I'm going crazy with aarlo.

i've add your code in my configuration.yaml
Please check if it's ok.



```
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_username
  password: !secret arlo_password
  mqtt_host: mqtt-cluster-z1.arloxcld.com
```

**Comment by twrecked** [comment]
Looks good.

**Comment by unecc** [comment]
Thanks, i've spend 1 month and the first time aarlo don't notify me an error.

Now where are my camera?

I've add a line for that
`aarlo:
  host: https://my.arlo.com
  username: !secret arlo_username
  password: !secret arlo_password
  mqtt_host: mqtt-cluster-z1.arloxcld.com
camera:
  platform: aarlo`

**Comment by unecc** [comment]
OK!!!
now i can see camera entities preview (but not live). Now i m try to make this

https://github.com/twrecked/lovelace-hass-aarlo/blob/master/hacsinstall.md

![image](https://github.com/twrecked/hass-aarlo/assets/134554559/6bba2f78-c909-4fbb-b841-a150ac7498be)

**Comment by unecc** [comment]
twkrecked thanks because thanks to your help I'm starting to see the end of the tunnel.
My real problem is the language and computer incompetence, the guide to aarlo seems difficult to me.

For the moment I have arrived here, I added everything the guide recommends.


```
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_username
  password: !secret arlo_password
  mqtt_host: mqtt-cluster-z1.arloxcld.com
  tfa_host: 'imap.gmail.com'
  tfa_username: !secret GV_USER
  tfa_password: !secret GV_PASS 

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8

camera:
  platform: aarlo
  
sensor:
  - platform: aarlo
    monitored_conditions:
      - total_cameras
      - last_capture
      - recent_activity
      - captured_today
      - battery_level
      - signal_strength
      - temperature
      - humidity
      - air_quality  
      
binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - ding
      - cry
      - connectivity

```
The result is this: play doesn't work and I'm not allowed to add

![image](https://github.com/twrecked/hass-aarlo/assets/134554559/8d6dbddf-c8f6-4dd6-baab-7f70ec9d53a6)

if I add show: and everything else gives me an error.

![image](https://github.com/twrecked/hass-aarlo/assets/134554559/0e5b1cee-6726-4126-9872-2131decfd945)
