### ISSUE TITLE
Video stream loading issues after 2-3 days of usage

### ISSUE THREAD

**Issue by matthieup240** [twrecked/hass-aarlo#815]
Hello and thank you for the work done on this integration. I'm using Arlo cameras with my Home Assistant setup and everything works well initially. However, after 2-3 days of usage, I notice the video stream loading time increasingly becomes longer, and sometimes it doesn't load at all. The only workaround I've found is to restart the server to regain a functional video stream.

```
aarlo:
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret arlo_user
  tfa_password: !secret arlo_gmail_password
  save_session: true
  backend: mqtt
  mqtt_host: mqtt-cluster-z1.arloxcld.com
  username: !secret arlo_user
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90

camera:
  - platform: aarlo
    #ffmpeg_arguments: "-pred 1 -q:v 2"
```

1. Do you have any suggestions on how to resolve this loading issue?
2. Are there any configuration parameters I should adjust to prevent this behavior?

Thank you in advance for your help and suggestions.
