### ISSUE TITLE
Fresh aarlo setup not working on startup

### ISSUE THREAD

**Issue by anachronox99** [twrecked/hass-aarlo#844]
I had a working HA setup with the aarlo integration all working. For a variety of reasons, I restored from a backup I did a week ago before setting up arlo, and tried to reinstall it. 

I installed both aarlo and the lovelace component using HACS. Restarted. All good. Then I updated the config file with the arlo config information, and after restarting, I get this error message. None of the arlo entities show up as a result. 

I see this in my notifications. 

<img width="341" alt="image" src="https://github.com/twrecked/hass-aarlo/assets/16225843/e7f542ef-338d-4cae-8217-f8858f9186c2">

**relevant parts of my config file**

```
alarm_control_panel:
  - platform: manual  
    code: xxxx
    code_arm_required: true
    name: Home alarm
    #pending_time: 3
    arming_time: 3
  - platform: aarlo
    away_mode_name: Armed
    disarmed_mode_name: Disarmed
    trigger_time: 30
    alarm_volume: 8
    
    
aarlo:
#  host: https://my.arlo.com
  username: xxx
  password: xxx
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%d-%m %H:%M'
  refresh_devices_every: 2
#  verbose_debug: True
#  packet_dump: True
  tfa_host: 'imap.gmail.com'
  tfa_username: xxx
  tfa_password: xxx
#  backend: sse

    
camera:
  - platform: aarlo

binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - ding
      - cry
      - connectivity

light:
  - platform: aarlo
  
switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    doorbell_silence: True
    siren_volume: 1
    siren_duration: 10

media_player:
  - platform: aarlo
```

**Log file:** 
[homeassistant.log](https://github.com/twrecked/hass-aarlo/files/13512076/homeassistant.log)

Any ideas? 

Thanks

aarlo Component Setup
Error: general-error=gaierror
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 497, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve

If error persists you might need to change config and restart.
