### ISSUE TITLE
Arlo/Aarlo cannot be activated / deactivation works.

### ISSUE THREAD

**Issue by mikburnz** [twrecked/hass-aarlo#863]
The mode cannot be switched to 'away' using the switch of the entity 'Base station alarm_control_panel.aarlo_base_station'; the field remains gray. When I activate it through the Arlo app, I can see the activated state in Home Assistant. Deactivation is then possible through Home Assistant. Communication seems to be working in one direction. The log shows the following:

2024-01-18 09:30:49.115 WARNING (SyncWorker_9) [pyaarlo] Base Station: mode 'home' is unrecognized.
2024-01-18 10:07:56.179 WARNING (SyncWorker_5) [pyaarlo] Base Station: mode 'away' is unrecognized.
2024-01-18 10:07:58.168 WARNING (SyncWorker_3) [pyaarlo] Base Station: mode 'away' is unrecognized.

**Comment by QuakeGio83** [comment]
I have the same problem, I can not arm/disarm the alarm from HA

**Comment by twrecked** [comment]
Is this still an issue. Try removing your `host` config setting.

**Comment by ynazar1** [comment]
Same thing here. Able to disarm but not arm...

Migrated from this: 
```
aarlo:
  username: !secret arlo.user
  password: !secret arlo.pass
  refresh_devices_every: 2
  stream_timeout: 120
  refresh_modes_every: 1
  reconnect_every: 30
  request_timeout: 120
  packet_dump: false
  backend: sse
  mqtt_hostname_check: False
  tfa_source: push
  tfa_type: PUSH

alarm_control_panel:
  - platform: aarlo

sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality
```

Getting `mode away` not recognized in logs
