### ISSUE TITLE
Unable to change alarm modes

### ISSUE THREAD

**Issue by herveaurel** [twrecked/hass-aarlo#931]
Hi,

Thanks for all that work !

I had a lot of difficulty migrating to the latest version, but after removing the integration, all files and codes, I finally succeeded.

Since version 0.8.1, it is impossible to change the doorbell alarm modes.

Before, there was no problem.

I've found that "_disarmed_" works, but that's it.

I tried with the Home Assistant alarm panel, with the "_aarlo.alarm_set_mode_" service, also I put a code, deleted the code... Nothing.

This is very unfortunate for automation...

```
Enregistreur: pyaarlo
Source: custom_components/aarlo/alarm_control_panel.py:342
intégration: Arlo Camera Support (documentation, problèmes)
S'est produit pour la première fois: 12:24:56 (36 occurrences)
Dernier enregistrement: 13:20:15

Arlo: mode away is unrecognised
Arlo: mode night is unrecognised
Arlo: mode home is unrecognised
Arlo: mode away_mode_away is unrecognised
Arlo: mode armed_away is unrecognised
```

THANKS

**Comment by twrecked** [comment]
It's working here - but isn't that always the case...

What was your original alarm configuration? Could you paste it here?

**Comment by herveaurel** [comment]
Thank you for your reply.

A friend who had the beta version for a long time has the same problem as me and he doesn't have an HA alarm...

My Home Assistant alarm?

```
  - platform: manual
    name: Alarme
    code: !secret alarme_code 
    code_arm_required: false
    arming_time: 50 
    delay_time: 20 
    armed_away: 
      arming_time: 50 
      delay_time: 20 
    armed_night: 
      arming_time: 0 
      delay_time: 20 
    disarmed:
      trigger_time: 0
```

In previous version (yaml), everything worked fine.

**Comment by twrecked** [comment]
I have the `aad1001` doorbell and it works fine so I think it should work for you.

I need your configuration for the Aarlo alarm. It would look something like this:

```yaml
- platform: aarlo 
  home_mode_name: home 
  away_mode_name: armed 
  night_mode_name: night
```

**Comment by twrecked** [comment]
Those values are now captured in the _Home Assistant_ configuration.  You can check to make sure they were imported correctly by running this command at the same level as your configuration files. The values should line up with what you are expecting. If not go to the integration page and click `CONFIGURE` on the _Aarlo_ page.

```sh
grep alarm_control_panel_ .storage/core.config_entries 
          "alarm_control_panel_disarmed_mode_name": "disarmed",
          "alarm_control_panel_home_mode_name": "home",
          "alarm_control_panel_away_mode_name": "away",
          "alarm_control_panel_night_mode_name": "night",
          "alarm_control_panel_code_arm_required": false,
          "alarm_control_panel_code_disarm_required": false,
          "alarm_control_panel_trigger_time": 60,
          "alarm_control_panel_alarm_volume": 3,
```

Do you mind pasting `/config/aarlo.yaml` in here as well. There could be something off in there.

And if this doesn't work I'll get you to collect some debug logs if that is ok.

**Comment by herveaurel** [comment]
> Do you mind pasting `/config/aarlo.yaml` in here as well. There could be something off in there.
> 
> And if this doesn't work I'll get you to collect some debug logs if that is ok.

I had correctly configured the integration configuration and the names seem to be correct.

![image](https://github.com/twrecked/hass-aarlo/assets/64784541/7fe26026-cebb-458f-8c86-4c57cd75795e)

Here is the file /config/aarlo.yaml : 

```
version: 1
aarlo:
  save_media_to: /media/Sonnette/${Y}/${m}/${F}-${T}
  backend: sse
```

**Comment by twrecked** [comment]
I didn't realise other people were having this issue... but I'm a bit snowed under with my real job.

One quick thing to try is to remove the `backend` setting.

Other than that, everything looks good. I guess I need some debug logs to see what is happening. Can you turn on [verbose debug](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#verbose-debug). You'll need to modify both `configuration.yaml` and `aarlo.yaml`.

You can [encrypt](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#online) the output and attach it to this bug report.

**Comment by herveaurel** [comment]
> I didn't realise other people were having this issue... but I'm a bit snowed under with my real job.
> 
> One quick thing to try is to remove the `backend` setting.
> 
> Other than that, everything looks good. I guess I need some debug logs to see what is happening. Can you turn on [verbose debug](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#verbose-debug). You'll need to modify both `configuration.yaml` and `aarlo.yaml`.
> 
> You can [encrypt](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#online) the output and attach it to this bug report.

I completely understand that with the extra work, it's difficult, and I admire developers like you, because thanks to you we can have superb integrations, and thank you.

I'm testing this...

Can you explain to me exactly what I need to do for the debug logs and I will do it but I don't think I understand everything?

**Comment by twrecked** [comment]
Make sure you have the following in `configuration.yaml`:

```yaml
logger:
  default: info
  logs:
    pyaarlo: debug
    custom_components.aarlo: debug
```

And make sure you have the following in `aarlo.yaml`

```yaml
aarlo:
  # current config here
  verbose_debug: True
```

Then restart _Home Assistant_. If you look in `home-assistant.log` you'll lots of extra debug coming out.

One more thing to try would be to add this to the config. It helped for one person.

```yaml
aarlo:
  .. usual stuff
  mode_api: v2
```
