### ISSUE TITLE
Can’t find aarlo.yaml

### ISSUE THREAD

**Issue by rpaillot** [twrecked/hass-aarlo#981]
Hi

I might sound stupid but I can’t find aarlo.yaml in my home assistant folder.
I use file editor to access the directory and I only find configuration.yaml which is my HA config file.

otherwise aarlo integration works perfectly but can’t tweak much things if I can’t find aarlo.yaml

this is what file editor shows me at the root of /homeassistant 
![IMG_9411](https://github.com/user-attachments/assets/31faf539-0682-494c-8758-17e2ea54ce65)

In custom components I have the aarlo directory with only .py files but not yaml.

In the root of home assistant like in the attached screen capture I only find .pickle files and cookies.txt

thanks for your help

**Comment by rpaillot** [comment]
only that ?

Then, Where can I tweak Aarlo Integration, especially regarding the video streaming ? 
Should I modify the .py files?

**Comment by twrecked** [comment]
You can add more entries to that file. For example I have:

```yaml
version: 1
aarlo:
  recent_time: 60
  refresh_devices_every: 1
  refresh_modes_every: 60
  stream_timeout: 125
  user_agent: linux
  reconnect_every: 15
  save_media_to: /config/media/${SN}/${Y}/${m}/${d}/${T}
```

If there isn't a value the code just uses a default.
